import type { Lang } from "@/lib/lang";

export const PLAYER_COPY = {
  IS: {
    header: {
      label: "Leikmaður",
    },
    tabs: {
      today: "Í dag",
      rpe: "RPE",
      dashboard: "Yfirlit",
      strength: "Styrkur",
      history: "Saga",
      vald: "VALD",
      chat: "Spjall",
      team: "Lið",
    },
    decision: {
      kicker: "Í dag",
      prefix: "Ákvörðun",
      coachMsg: "Skilaboð frá þjálfara",
      why: "Af hverju:",
      readyTitle: "Tilbúinn til æfingar",
      readyBody: "Þú ert leyfður í fulla þjálfun í dag.",
      readyFollow: "Fylgdu áætlaðri æfingu.",
      sessionBtn: "Fulla æfing",
    },
    training: {
      sectionTitle: "Æfing dagsins",
      status: "Staða",
      noItems: "Engin atriði í þessum hluta.",
      loading: "Hleð gögnum...",
      changeExercise: "Ef þú vilt breyta, veldu aðra æfingu",
      origPlan: "Upprunalegt plan:",
      otherOptions: "Aðrir valkostir",
      useRecommended: "Nota mælt með",
      notRecommended: "Ekki ráðlagt í dag:",
    },
    rpe: {
      kicker: "Eftir æfingu",
      title: "Post-Session RPE",
      sub: "Mettu hversu þungt heildaræfingin leyndist.",
    },
    readiness: {
      title: "Mælingar dagsins",
      sub: "Aðeins til upplýsingar — notað fyrir ákvörðunarlógík.",
    },
    blocks: {
      warmup: "Upphitun",
      primer: "Primer",
      main: "Main",
      accessory: "Accessory",
      part: "Partur",
    },
    session: {
      ack: "Mætt",
      complete: "Lokið",
      seen: "Skoðað",
    },
    misc: {
      noData: "Engin gögn",
      noBaseline: "No baseline",
      override: "Override",
      loading: "Hleð…",
      locked: "Læst",
      unlocked: "Ólæst",
      open: "Opna",
      close: "Loka",
      playerFallback: "Leikmaður",
      section: (n: number) => `Hluti ${n}`,
      noDataTitle: "Engar líðansgögn í dag",
      noDataBody: "Þú hefur ekki skráð líðan þína í dag enn. Skráðu líðan til að fá dagleg ráð og þjálfunaráætlun.",
      noDataBtn: "Skrá líðan núna",
    },
    checkin: {
      missingTitle: "Dagleg skráning vantar",
      missingBody: "Skráðu líðan þína til að kerfið geti stillt æfinguna fyrir þig í dag.",
      missingBtn: "Skrá núna →",
    },
    postTraining: {
      kicker: "Eftir æfingu",
      title: "Mælt með",
      sub: "5–10 mínútur til að styðja sinar og taugakerfi eftir æfingu.",
      count: (n: number) => `${n} rútín${n === 1 ? "a" : "ur"}`,
      empty: "Engar tillögur í dag.",
      noSteps: "Engin skref í template.",
      open: "Opna",
      close: "Loka",
      durationMin: (min: number) => `${min} mín`,
    },
  },
  EN: {
    header: {
      label: "Player",
    },
    tabs: {
      today: "Today",
      rpe: "RPE",
      dashboard: "Dashboard",
      strength: "Strength",
      history: "History",
      vald: "VALD",
      chat: "Chat",
      team: "Team",
    },
    decision: {
      kicker: "Today",
      prefix: "Decision",
      coachMsg: "Message from coach",
      why: "Why:",
      readyTitle: "Ready to Train",
      readyBody: "You are cleared for full training today.",
      readyFollow: "Follow today's planned session.",
      sessionBtn: "Full session",
    },
    training: {
      sectionTitle: "Today's Session",
      status: "Status",
      noItems: "No items in this section.",
      loading: "Loading...",
      changeExercise: "Change exercise — select another option",
      origPlan: "Original plan:",
      otherOptions: "Other options",
      useRecommended: "Use recommended",
      notRecommended: "Not recommended today:",
    },
    rpe: {
      kicker: "Post-Session",
      title: "Post-Session RPE",
      sub: "Rate how hard the full session felt overall.",
    },
    readiness: {
      title: "Today's Measurements",
      sub: "For reference only — used for decision logic.",
    },
    blocks: {
      warmup: "Warm-up",
      primer: "Primer",
      main: "Main",
      accessory: "Accessory",
      part: "Section",
    },
    session: {
      ack: "Attended",
      complete: "Complete",
      seen: "Seen",
    },
    misc: {
      noData: "No data",
      noBaseline: "No baseline",
      override: "Override",
      loading: "Loading…",
      locked: "Locked",
      unlocked: "Unlocked",
      open: "Show",
      close: "Hide",
      playerFallback: "Player",
      section: (n: number) => `Section ${n}`,
      noDataTitle: "No wellness data today",
      noDataBody: "You haven't submitted your wellness today. Submit to receive daily guidance and your training plan.",
      noDataBtn: "Submit wellness now",
    },
    checkin: {
      missingTitle: "Daily check-in missing",
      missingBody: "Submit your wellness so the system can tailor today's session for you.",
      missingBtn: "Check in now →",
    },
    postTraining: {
      kicker: "After session",
      title: "Recommended",
      sub: "5–10 minutes to support tendons and the nervous system after training.",
      count: (n: number) => `${n} routine${n === 1 ? "" : "s"}`,
      empty: "No suggestions today.",
      noSteps: "No steps in template.",
      open: "Show",
      close: "Hide",
      durationMin: (min: number) => `${min} min`,
    },
  },
} satisfies Record<Lang, object>;

export type PlayerCopy = (typeof PLAYER_COPY)["IS"];
