import type { Lang } from "@/lib/lang";

export const PLAYER_COPY = {
  IS: {
    header: {
      label: "Leikmaður",
    },
    tabs: {
      today: "Í dag",
      rpe: "RPE",
      dashboard: "Yfirlit",
      strength: "Styrkur",
      gamereport: "Leikur",
      movement: "Hreyfing",
      stats: "Fótbolti",
      history: "Saga",
      vald: "VALD",
      chat: "Spjall",
      team: "Lið",
      privacy: "Friðhelgi",
    },
    decision: {
      kicker: "Í dag",
      prefix: "Ákvörðun",
      coachMsg: "Skilaboð frá þjálfara",
      why: "Af hverju:",
      readyTitle: "Tilbúinn til æfingar",
      readyBody: "Þú ert leyfður í fulla þjálfun í dag.",
      readyFollow: "Fylgdu áætlaðri æfingu.",
      sessionBtn: "Fulla æfing",
      behind: {
        toggle: "Á bak við tölurnar",
        measuresLabel: "Hvað þetta mælir",
        measures: "Hvernig dagurinn í dag ber saman við þitt eigið venjulega — ekki við aðra leikmenn.",
        howLabel: "Hvernig það er reiknað",
        how: "Líðan (þín check-in), æfingaálag og leikminni, borið saman við þína persónulegu grunnlínu.",
        signalsLabel: "Merkin á bak við",
        confidenceLabel: "Traust",
        confidenceHasBaseline: "Byggt á þinni eigin grunnlínu. Því fleiri check-in, því skarpari verður matið.",
        confidenceNoBaseline: "Grunnlínan þín er enn að byggjast upp — matið verður öruggara með fleiri check-in.",
        caveatLabel: "Fyrirvari",
        caveat: "Þetta er samhengi um reiðu og álagsbreytingu — ekki spá um meiðsli. Álagshlutfall (ACWR) sýnir stærð breytingar, ekki áhættu.",
        cite: "Gabbett 2017 · persónuleg grunnlína",
      },
    },
    checkin: {
      explainTitle: "Af hverju við spyrjum",
      subtitle: "30 sek. — skýr merki gefa betri ákvörðun og læsta dagsæfingu.",
      q: {
        fatigue: {
          title: "Orka / þreyta",
          desc: "Hvernig er orkan í dag?",
          why: "Þín eigin tilfinning fyrir orku er sterkasta dag-frá-degi merkið um reiðu — hún nemur uppsafnaða þreytu áður en hún sést í gögnunum.",
          src: "Saw o.fl. 2016",
        },
        sleepQuality: {
          title: "Svefngæði",
          desc: "Hvernig svafstu í nótt?",
          why: "Lélegur svefn hægir á endurheimt og eykur líkur á meiðslum og veikindum daginn eftir — meira en flestir æfingaþættir.",
          src: "Fullagar 2015; Watson 2017",
        },
        sleepDuration: {
          title: "Svefnlengd",
          desc: "Hversu lengi svafstu?",
          why: "Undir ~7 klst. færir þig í átt að vanendurheimt. Heildarklukkustundirnar telja samhliða því hversu úthvíld/ur þú finnur þig.",
          src: "Milewski 2014 (<8 klst. → hærri meiðslatíðni)",
        },
        stressMood: {
          title: "Streita / líðan",
          desc: "Hvernig er hausinn í dag?",
          why: "Álag utan vallar keppir við æfingar um sömu endurheimtargetu — háir streitudagar þola minna álag, jafnvel þótt líkaminn sé í lagi.",
          src: "Mann o.fl. 2016",
        },
        soreness: {
          title: "Eymsli í vöðvum",
          desc: "Hvað ertu aum/ur eftir síðustu æfingu?",
          why: "Eymsli benda á vef sem er enn í viðgerð. Að æfa hart ofan á það er einmitt þegar tognanir gerast.",
          src: "Hough 2019",
        },
      },
      notesTitle: "Athugasemd (valfrjálst)",
      notesDesc: "Ef eitthvað skiptir máli (meiðsli, veikindi, streita) skrifaðu hér — kerfið les það og getur stungið upp á breytingum.",
      missingTitle: "Dagleg skráning vantar",
      missingBody: "Skráðu líðan þína til að kerfið geti stillt æfinguna fyrir þig í dag.",
      missingBtn: "Skrá núna →",
    },
    training: {
      sectionTitle: "Æfing dagsins",
      status: "Staða",
      noItems: "Engin atriði í þessum hluta.",
      loading: "Hleð gögnum...",
      changeExercise: "Ef þú vilt breyta, veldu aðra æfingu",
      origPlan: "Upprunalegt plan:",
      otherOptions: "Aðrir valkostir",
      useRecommended: "Nota mælt með",
      notRecommended: "Ekki ráðlagt í dag:",
    },
    rpe: {
      kicker: "Eftir æfingu",
      title: "Post-Session RPE",
      sub: "Mettu hversu þungt heildaræfingin leyndist.",
    },
    readiness: {
      title: "Mælingar dagsins",
      sub: "Aðeins til upplýsingar — notað fyrir ákvörðunarlógík.",
    },
    blocks: {
      warmup: "Upphitun",
      primer: "Primer",
      main: "Main",
      accessory: "Accessory",
      part: "Partur",
    },
    session: {
      ack: "Mætt",
      complete: "Lokið",
      seen: "Skoðað",
    },
    misc: {
      noData: "Engin gögn",
      noBaseline: "No baseline",
      override: "Override",
      loading: "Hleð…",
      locked: "Læst",
      unlocked: "Ólæst",
      open: "Opna",
      close: "Loka",
      playerFallback: "Leikmaður",
      section: (n: number) => `Hluti ${n}`,
      noDataTitle: "Engar líðansgögn í dag",
      noDataBody: "Þú hefur ekki skráð líðan þína í dag enn. Skráðu líðan til að fá dagleg ráð og þjálfunaráætlun.",
      noDataBtn: "Skrá líðan núna",
    },
    postTraining: {
      kicker: "Eftir æfingu",
      title: "Mælt með",
      sub: "5–10 mínútur til að styðja sinar og taugakerfi eftir æfingu.",
      count: (n: number) => `${n} rútín${n === 1 ? "a" : "ur"}`,
      empty: "Engar tillögur í dag.",
      noSteps: "Engin skref í template.",
      open: "Opna",
      close: "Loka",
      durationMin: (min: number) => `${min} mín`,
      // Redesigned time-gated Reload hero + focus flow
      statusReady: "TILBÚIÐ",
      statusPassed: "LIÐIÐ HJÁ",
      readyNow: "TILBÚIÐ NÚNA",
      pendingLabel: "Eftir æfinguna",
      passedLabel: "Besti glugginn liðinn",
      reloadName: "Tendon Reload",
      reloadDesc: "Æfing búin 💪 — sinar haldið meðan þú ert enn heit(ur), svo neural reset til að róa taugakerfið.",
      whenReady: "Best á næstu 30 mín meðan þú ert enn heit(ur).",
      whenPending: "Gerðu hana strax eftir æfinguna — skráðu RPE til að ræsa gluggann.",
      whenPassed: "Besti glugginn er liðinn, en þú mátt enn gera hana.",
      minsLeft: (n: number) => `~${n} mín eftir af glugganum`,
      startCta: "Byrja Reload →",
      footnote: "Reload er tímaháð aðgerð — hún á aðeins við eftir æfingu. Læsingin gerir hana að náttúrulegu næsta skrefi frekar en enn einu korti sem situr aðgerðalaust allan daginn.",
      focusTitle: "Reload",
      finishTitle: "Reload lokið",
      finishBody: "Vel gert. Taugakerfið er í niðurstillingu — dagurinn má klárast rólega.",
      finishClose: "Loka",
      back: "Til baka",
      next: "Næst",
      continueCta: "Áfram →",
      finishCta: "Klára ✓",
      stepOf: (a: number, b: number) => `${a} af ${b}`,
      tagTendon: "Tendon load",
      tagNeural: "Neural reset",
      setsLabel: "Sett",
      holdLabel: "Hald",
      restLabel: "Hvíld",
      altLabel: "Val",
    },
  },
  EN: {
    header: {
      label: "Player",
    },
    tabs: {
      today: "Today",
      rpe: "RPE",
      dashboard: "Dashboard",
      strength: "Strength",
      gamereport: "Match",
      movement: "Movement",
      stats: "Football",
      history: "History",
      vald: "VALD",
      chat: "Chat",
      team: "Team",
      privacy: "Privacy",
    },
    decision: {
      kicker: "Today",
      prefix: "Decision",
      coachMsg: "Message from coach",
      why: "Why:",
      readyTitle: "Ready to Train",
      readyBody: "You are cleared for full training today.",
      readyFollow: "Follow today's planned session.",
      sessionBtn: "Full session",
      behind: {
        toggle: "Behind the numbers",
        measuresLabel: "What this measures",
        measures: "How today compares to your own usual — not to other players.",
        howLabel: "How it's computed",
        how: "Wellness (your check-in), training load and match minutes, compared to your personal baseline.",
        signalsLabel: "Signals behind it",
        confidenceLabel: "Confidence",
        confidenceHasBaseline: "Based on your own baseline. The more check-ins you log, the sharper this gets.",
        confidenceNoBaseline: "Your baseline is still building — the assessment sharpens with more check-ins.",
        caveatLabel: "Caveat",
        caveat: "This is readiness and load-change context — not an injury prediction. The load ratio (ACWR) shows the size of a change, not risk.",
        cite: "Gabbett 2017 · personal baseline",
      },
    },
    checkin: {
      explainTitle: "Why we ask",
      subtitle: "30 sec — clear signals give a better decision and a locked session plan.",
      q: {
        fatigue: {
          title: "Energy / fatigue",
          desc: "How's your energy today?",
          why: "Your own sense of energy is the strongest day-to-day readiness signal — it catches accumulated fatigue before it shows up in the data.",
          src: "Saw et al. 2016",
        },
        sleepQuality: {
          title: "Sleep quality",
          desc: "How did you sleep last night?",
          why: "Poor sleep quality blunts recovery and raises next-day injury and illness risk — more than most training variables.",
          src: "Fullagar 2015; Watson 2017",
        },
        sleepDuration: {
          title: "Sleep duration",
          desc: "How long did you sleep?",
          why: "Under ~7h tips you toward under-recovery. The total hours matter alongside how rested you feel.",
          src: "Milewski 2014 (<8h → higher injury rate)",
        },
        stressMood: {
          title: "Stress / mood",
          desc: "How's your head today?",
          why: "Life stress competes with training for the same recovery capacity — high-stress days need lighter load even if your body feels fine.",
          src: "Mann et al. 2016",
        },
        soreness: {
          title: "Muscle soreness",
          desc: "How sore are you after the last session?",
          why: "Soreness flags tissue that's still repairing. Training hard on top of it is exactly when strains happen.",
          src: "Hough 2019",
        },
      },
      notesTitle: "Note (optional)",
      notesDesc: "If something matters (injury, illness, stress) write it here — the system reads it and can suggest changes.",
      missingTitle: "Daily check-in missing",
      missingBody: "Submit your wellness so the system can tailor today's session for you.",
      missingBtn: "Check in now →",
    },
    training: {
      sectionTitle: "Today's Session",
      status: "Status",
      noItems: "No items in this section.",
      loading: "Loading...",
      changeExercise: "Change exercise — select another option",
      origPlan: "Original plan:",
      otherOptions: "Other options",
      useRecommended: "Use recommended",
      notRecommended: "Not recommended today:",
    },
    rpe: {
      kicker: "Post-Session",
      title: "Post-Session RPE",
      sub: "Rate how hard the full session felt overall.",
    },
    readiness: {
      title: "Today's Measurements",
      sub: "For reference only — used for decision logic.",
    },
    blocks: {
      warmup: "Warm-up",
      primer: "Primer",
      main: "Main",
      accessory: "Accessory",
      part: "Section",
    },
    session: {
      ack: "Attended",
      complete: "Complete",
      seen: "Seen",
    },
    misc: {
      noData: "No data",
      noBaseline: "No baseline",
      override: "Override",
      loading: "Loading…",
      locked: "Locked",
      unlocked: "Unlocked",
      open: "Show",
      close: "Hide",
      playerFallback: "Player",
      section: (n: number) => `Section ${n}`,
      noDataTitle: "No wellness data today",
      noDataBody: "You haven't submitted your wellness today. Submit to receive daily guidance and your training plan.",
      noDataBtn: "Submit wellness now",
    },
    postTraining: {
      kicker: "After session",
      title: "Recommended",
      sub: "5–10 minutes to support tendons and the nervous system after training.",
      count: (n: number) => `${n} routine${n === 1 ? "" : "s"}`,
      empty: "No suggestions today.",
      noSteps: "No steps in template.",
      open: "Show",
      close: "Hide",
      durationMin: (min: number) => `${min} min`,
      // Redesigned time-gated Reload hero + focus flow
      statusReady: "READY",
      statusPassed: "WINDOW PASSED",
      readyNow: "READY NOW",
      pendingLabel: "After your session",
      passedLabel: "Best window passed",
      reloadName: "Tendon Reload",
      reloadDesc: "Session done 💪 — tendon holds while you're warm, then a neural reset to settle the nervous system.",
      whenReady: "Best in the next 30 min while you're still warm.",
      whenPending: "Do it right after your session — log your RPE to start the window.",
      whenPassed: "The best window has passed, but you can still run it.",
      minsLeft: (n: number) => `~${n} min left in the window`,
      startCta: "Start Reload →",
      footnote: "Reload is time-sensitive — it only applies right after training. The lock makes it the natural next step rather than one more card sitting idle all day.",
      focusTitle: "Reload",
      finishTitle: "Reload complete",
      finishBody: "Nice work. The nervous system is downshifting — the rest of the day can settle.",
      finishClose: "Close",
      back: "Back",
      next: "Next",
      continueCta: "Continue →",
      finishCta: "Finish ✓",
      stepOf: (a: number, b: number) => `${a} of ${b}`,
      tagTendon: "Tendon load",
      tagNeural: "Neural reset",
      setsLabel: "Sets",
      holdLabel: "Hold",
      restLabel: "Rest",
      altLabel: "Alternative",
    },
  },
} satisfies Record<Lang, object>;

export type PlayerCopy = (typeof PLAYER_COPY)["IS"];
