export const TRAINER_COPY = {
  IS: {
    tabs: {
      clients: "Skjólstæðingar",
      plans: "Áætlanir",
      exercises: "Æfingasafn",
      invitations: "Boð",
    },
    header: {
      title: "Einkaþjálfun",
      subtitle: "Yfirlit skjólstæðinga",
    },
    clients: {
      noClients: "Engir skjólstæðingar skráðir. Sendu boð til að byrja.",
      addClient: "Bæta við skjólstæðingi",
      checkedIn: "Skráður inn",
      notCheckedIn: "Ekki skráður",
      noAccount: "Ekki með aðgang",
      noPlan: "Engin áætlun",
      todayDone: "Lokið í dag",
      viewDetails: "Skoða",
    },
    readiness: {
      green: "Tilbúinn",
      yellow: "Gát",
      red: "Hvíld",
      none: "Engin gögn",
    },
    invitations: {
      title: "Boð til skjólstæðinga",
      send: "Senda boð",
      pending: "Í bið",
      accepted: "Samþykkt",
      expired: "Útrunnið",
      revoked: "Afturkallað",
      email: "Netfang",
      name: "Nafn",
      revoke: "Afturkalla",
      copyLink: "Afrita tengil",
      linkCopied: "Tengill afritaður",
    },
    plan: {
      strength: "Styrktarþjálfun",
      endurance: "Þolþjálfun",
      mixed: "Blandað",
      createPlan: "Búa til áætlun",
    },
    plans: {
      createTemplate: "Búa til nýtt sniðmát",
      editTemplate: "Breyta sniðmáti",
      templateName: "Nafn sniðmáts",
      planType: "Tegund áætlunar",
      duration: "Lengd",
      sessionsPerWeek: "Setumál á viku",
      readiness: "Geta til þjálfunar",
      readinessSettings: "Stillingar getu til þjálfunar",
      sets: "Set",
      reps: "Endurtekningar",
      load: "Þyngd",
      loadType: "Tegund þyngdar",
      tempo: "Hraði",
      rest: "Hvíld",
      notes: "Athugasemdir",
      searchExercises: "Leita að æfingum",
      save: "Vista",
      assignPlan: "Úthluta áætlun",
      selectClient: "Veldu skjólstæðing",
      startDate: "Byrjunardagur",
      tweakLoadValues: "Breyta þyngdargildum",
      createNew: "Búa til nýja",
      edit: "Breyta",
      delete: "Eyða",
      noPlan: "Engin sniðmát búin til ennþá",
      noPlanAssignments: "Engar virkar áætlanir",
    },
    load: {
      acwr: "ACWR",
      rising: "Hækkandi",
      stable: "Stöðugt",
      dropping: "Lækkandi",
    },
  },
  EN: {
    tabs: {
      clients: "Clients",
      plans: "Plans",
      exercises: "Exercise Library",
      invitations: "Invitations",
    },
    header: {
      title: "Personal Training",
      subtitle: "Client overview",
    },
    clients: {
      noClients: "No clients registered. Send an invitation to get started.",
      addClient: "Add client",
      checkedIn: "Checked in",
      notCheckedIn: "Not checked in",
      noAccount: "No account",
      noPlan: "No plan",
      todayDone: "Done today",
      viewDetails: "View",
    },
    readiness: {
      green: "Ready",
      yellow: "Caution",
      red: "Recovery",
      none: "No data",
    },
    invitations: {
      title: "Client invitations",
      send: "Send invitation",
      pending: "Pending",
      accepted: "Accepted",
      expired: "Expired",
      revoked: "Revoked",
      email: "Email",
      name: "Name",
      revoke: "Revoke",
      copyLink: "Copy link",
      linkCopied: "Link copied",
    },
    plan: {
      strength: "Strength",
      endurance: "Endurance",
      mixed: "Mixed",
      createPlan: "Create plan",
    },
    plans: {
      createTemplate: "Create new template",
      editTemplate: "Edit template",
      templateName: "Template name",
      planType: "Plan type",
      duration: "Duration",
      sessionsPerWeek: "Sessions per week",
      readiness: "Readiness",
      readinessSettings: "Readiness settings",
      sets: "Sets",
      reps: "Reps",
      load: "Load",
      loadType: "Load type",
      tempo: "Tempo",
      rest: "Rest",
      notes: "Notes",
      searchExercises: "Search exercises",
      save: "Save",
      assignPlan: "Assign plan",
      selectClient: "Select a client",
      startDate: "Start date",
      tweakLoadValues: "Tweak load values",
      createNew: "Create new",
      edit: "Edit",
      delete: "Delete",
      noPlan: "No templates created yet",
      noPlanAssignments: "No active plan assignments",
    },
    load: {
      acwr: "ACWR",
      rising: "Rising",
      stable: "Stable",
      dropping: "Dropping",
    },
  },
} as const;

export type TrainerLang = keyof typeof TRAINER_COPY;
