export const TRAINER_COPY = {
  IS: {
    tabs: {
      clients: "Skjólstæðingar",
      plans: "Áætlanir",
      exercises: "Æfingasafn",
      invitations: "Boð",
    },
    header: {
      title: "Einkaþjálfun",
      subtitle: "Yfirlit skjólstæðinga",
    },
    clients: {
      noClients: "Engir skjólstæðingar skráðir. Sendu boð til að byrja.",
      addClient: "Bæta við skjólstæðingi",
      checkedIn: "Skráður inn",
      notCheckedIn: "Ekki skráður",
      noAccount: "Ekki með aðgang",
      noPlan: "Engin áætlun",
      todayDone: "Lokið í dag",
      viewDetails: "Skoða",
    },
    readiness: {
      green: "Tilbúinn",
      yellow: "Gát",
      red: "Hvíld",
      none: "Engin gögn",
    },
    invitations: {
      title: "Boð til skjólstæðinga",
      send: "Senda boð",
      pending: "Í bið",
      accepted: "Samþykkt",
      expired: "Útrunnið",
      revoked: "Afturkallað",
      email: "Netfang",
      name: "Nafn",
      revoke: "Afturkalla",
      copyLink: "Afrita tengil",
      linkCopied: "Tengill afritaður",
    },
    plan: {
      strength: "Styrktarþjálfun",
      endurance: "Þolþjálfun",
      mixed: "Blandað",
      createPlan: "Búa til áætlun",
    },
    load: {
      acwr: "ACWR",
      rising: "Hækkandi",
      stable: "Stöðugt",
      dropping: "Lækkandi",
    },
  },
  EN: {
    tabs: {
      clients: "Clients",
      plans: "Plans",
      exercises: "Exercise Library",
      invitations: "Invitations",
    },
    header: {
      title: "Personal Training",
      subtitle: "Client overview",
    },
    clients: {
      noClients: "No clients registered. Send an invitation to get started.",
      addClient: "Add client",
      checkedIn: "Checked in",
      notCheckedIn: "Not checked in",
      noAccount: "No account",
      noPlan: "No plan",
      todayDone: "Done today",
      viewDetails: "View",
    },
    readiness: {
      green: "Ready",
      yellow: "Caution",
      red: "Recovery",
      none: "No data",
    },
    invitations: {
      title: "Client invitations",
      send: "Send invitation",
      pending: "Pending",
      accepted: "Accepted",
      expired: "Expired",
      revoked: "Revoked",
      email: "Email",
      name: "Name",
      revoke: "Revoke",
      copyLink: "Copy link",
      linkCopied: "Link copied",
    },
    plan: {
      strength: "Strength",
      endurance: "Endurance",
      mixed: "Mixed",
      createPlan: "Create plan",
    },
    load: {
      acwr: "ACWR",
      rising: "Rising",
      stable: "Stable",
      dropping: "Dropping",
    },
  },
} as const;

export type TrainerLang = keyof typeof TRAINER_COPY;
