import type { PdfRenderModel, ReportDocument } from "./types";

/** Converts report document into a PDF-friendly structural model. */
export function buildPdfRenderModel(report: ReportDocument): PdfRenderModel {
  return {
    title: report.title,
    subtitle: `${report.audience} · ${report.scope}`,
    generatedAt: report.generatedAt ?? null,
    summaryLine: report.summaryLine,
    sections: report.sections.map((section) => ({
      title: section.title,
      kind: section.kind,
      rows: Array.isArray(section.data) ? section.data : undefined,
      text: typeof section.data === "string" ? [section.data] : Array.isArray(section.data) ? undefined : [JSON.stringify(section.data)],
    })),
    footerNote: "Generated by MicroPulse reporting layer.",
  };
}
