/**
 * GET /api/player/today-strength-default
 *
 * Read-time DEFAULT micro-dose for the player's Today card, generated by the
 * strength engine from the exercise library + MD templates — NO template table
 * required. This closes the gap where a team with neither a coach-sent session
 * nor its own custom programme (the shared microdose_templates table is only
 * populated for one club) would see no strength at all. Lite teams need only a
 * readiness check-in + week setup (MD context), which the engine already runs on.
 *
 * IMPORTANT — this is a DISPLAY fallback, not auto-send:
 *   - It does NOT persist anything (no player_today_strength_override write) and
 *     fires no push/message. It is only consulted by PlayerClient when every
 *     real source (coach-sent, custom programme, team template) came back empty.
 *   - The engine returns null on OFF / MD+2 / MD+3-rest days, and a rehab-only
 *     (empty) session for injured / RECOVERY players — both surface here as
 *     "no default" (structure: null), so strength never appears when it shouldn't.
 *   - "standard" mode: the clean squad MD template, readiness- and MD-tuned, with
 *     none of the per-player individualisation layers (which a bare Lite team has
 *     no data for anyway).
 *
 * Auth: player bearer token (same as the other /api/player routes).
 */

import { NextRequest, NextResponse } from "next/server";
import { getSupabaseAdmin } from "@/lib/supabase-admin";
import { requireAuthedPlayerId, getPlayerTeamId } from "@/lib/session-rpe/server";
import { loadPlayerStrengthSnapshot } from "@/lib/micropulse/strengthProgramming/loader";
import { buildStrengthSession } from "@/lib/micropulse/strengthProgramming";
import { strengthSessionToTodayStructure } from "@/lib/micropulse/strengthProgramming/toTodayStructure";

export const runtime = "nodejs";

const todayIso = () => new Date().toISOString().slice(0, 10);

export async function GET(req: NextRequest) {
  try {
    const sb = getSupabaseAdmin();
    const { playerId } = await requireAuthedPlayerId(sb, req);
    const teamId = await getPlayerTeamId(sb, playerId);

    const url = new URL(req.url);
    const dayParam = url.searchParams.get("day");
    const day = dayParam && /^\d{4}-\d{2}-\d{2}$/.test(dayParam) ? dayParam : todayIso();
    const lang: "EN" | "IS" = String(url.searchParams.get("lang") ?? "").toUpperCase() === "IS" ? "IS" : "EN";

    const snapshot = await loadPlayerStrengthSnapshot(sb, {
      playerId,
      teamId,
      todayIso: day,
      mdContextOverride: null, // auto MD from week_plans (defaults to MD-3)
    });

    // Standard mode = the clean squad MD template, still readiness/MD-tuned.
    const session = buildStrengthSession(snapshot, [], { mode: "standard" });
    if (!session) {
      // OFF / MD+2 / MD+3-rest — no strength day.
      return NextResponse.json({ ok: true, structure: null, reason: "no-session" });
    }

    const structure = strengthSessionToTodayStructure(session, lang);
    if (!structure.length) {
      // Injured (rehab-only) or RECOVERY/HOLD (stripped) → nothing to show.
      return NextResponse.json({ ok: true, structure: null, reason: "empty" });
    }

    return NextResponse.json({
      ok: true,
      structure,
      mdContext: session.mdContext,
      title: lang === "IS" ? "Sjálfgefin styrktaræfing" : "Default strength session",
      description: (lang === "IS" ? session.summaryIS : session.summaryEN) ?? null,
      summary: (lang === "IS" ? session.summaryIS : session.summaryEN) ?? null,
      durationMin: session.durationMin ?? null,
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : "Unknown error";
    const status = msg === "Unauthorized" ? 401 : 500;
    return NextResponse.json({ ok: false, error: msg }, { status });
  }
}
