import type {
  ExerciseDefinition,
  MdContext,
  TrainingBlueprint,
  TrainingNodeDefinition,
  VelocityZoneKey,
} from "./types";

export const VELOCITY_LOSS_LIMITS_BY_MD: Record<MdContext, number | null> = {
  MD5: 0.2,
  MD4: 0.2,
  MD3: 0.15,
  MD2: 0.1,
  MD1: 0.05,
  MD_PLUS_1: 0.05,
  OFF: null,
  UNKNOWN: null,
};

export const VELOCITY_ZONES: Record<VelocityZoneKey, { min: number | null; max: number | null }> = {
  MAX_STRENGTH: { min: 0.55, max: 0.7 },
  STRENGTH: { min: 0.65, max: 0.85 },
  STRENGTH_SPEED: { min: 0.75, max: 0.95 },
  POWER: { min: 0.9, max: 1.1 },
  BALLISTIC: { min: 1.1, max: null },
  NONE: { min: null, max: null },
};

export const EXERCISE_LIBRARY: Record<string, ExerciseDefinition> = {
  jump_shrug: {
    id: "jump_shrug",
    title: "Jump Shrug",
    category: "primer",
    movementPattern: "jump",
    nodeTypes: ["primer_ballistic"],
    velocitySupported: true,
    defaultVelocity: { zoneKey: "BALLISTIC", targetMin: 1.1, targetMax: null, velocityLossCap: 0.1 },
    tags: ["ballistic", "cluster"],
  },
  mid_thigh_pull: {
    id: "mid_thigh_pull",
    title: "Mid-Thigh Pull",
    category: "strength",
    movementPattern: "hinge",
    nodeTypes: ["primer_ballistic", "main_force_contrast"],
    velocitySupported: true,
    bilateral: true,
    defaultVelocity: { zoneKey: "POWER", targetMin: 0.9, targetMax: 1.1, velocityLossCap: 0.1 },
  },
  db_snatch: {
    id: "db_snatch",
    title: "DB Snatch",
    category: "primer",
    movementPattern: "pull",
    nodeTypes: ["primer_ballistic"],
    velocitySupported: true,
    unilateral: true,
    defaultVelocity: { zoneKey: "BALLISTIC", targetMin: 1.1, targetMax: null, velocityLossCap: 0.1 },
  },
  iso_mid_thigh_pull: {
    id: "iso_mid_thigh_pull",
    title: "ISO Mid-Thigh Pull",
    category: "isometric",
    movementPattern: "hinge",
    nodeTypes: ["support_isometric"],
    velocitySupported: false,
  },
  trap_bar_deadlift: {
    id: "trap_bar_deadlift",
    title: "Trap Bar Deadlift",
    category: "strength",
    movementPattern: "hinge",
    nodeTypes: ["main_force", "main_force_contrast"],
    velocitySupported: true,
    bilateral: true,
    defaultVelocity: { zoneKey: "STRENGTH", targetMin: 0.7, targetMax: 0.75, velocityLossCap: 0.1 },
  },
  split_stance_trap_bar_deadlift: {
    id: "split_stance_trap_bar_deadlift",
    title: "Split-Stance Trap Bar Deadlift",
    category: "strength",
    movementPattern: "split_squat",
    nodeTypes: ["main_force", "main_force_contrast"],
    velocitySupported: true,
    unilateral: true,
    defaultVelocity: { zoneKey: "STRENGTH", targetMin: 0.7, targetMax: 0.75, velocityLossCap: 0.1 },
  },
  rfess: {
    id: "rfess",
    title: "RFESS",
    category: "strength",
    movementPattern: "split_squat",
    nodeTypes: ["main_force_contrast", "support_isometric"],
    velocitySupported: true,
    unilateral: true,
    defaultVelocity: { zoneKey: "STRENGTH", targetMin: 0.7, targetMax: 0.75, velocityLossCap: 0.1 },
  },
  box_jump: {
    id: "box_jump",
    title: "Box Jump",
    category: "plyometric",
    movementPattern: "jump",
    nodeTypes: ["main_force_contrast", "primer_ballistic"],
    velocitySupported: false,
  },
  drop_jump: {
    id: "drop_jump",
    title: "Drop Jump",
    category: "plyometric",
    movementPattern: "jump",
    nodeTypes: ["main_force_contrast", "primer_ballistic"],
    velocitySupported: false,
  },
  hamstring_iso: {
    id: "hamstring_iso",
    title: "Hamstring ISO",
    category: "isometric",
    movementPattern: "hamstring",
    nodeTypes: ["support_isometric", "recovery_reset"],
    velocitySupported: false,
  },
  copenhagen_iso: {
    id: "copenhagen_iso",
    title: "Copenhagen ISO",
    category: "isometric",
    movementPattern: "adductor",
    nodeTypes: ["support_isometric", "recovery_reset"],
    velocitySupported: false,
  },
  ankle_iso: {
    id: "ankle_iso",
    title: "Ankle ISO",
    category: "isometric",
    movementPattern: "ankle",
    nodeTypes: ["support_isometric", "recovery_reset"],
    velocitySupported: false,
  },
  mini_band_glute_walk: {
    id: "mini_band_glute_walk",
    title: "Mini Band Glute Walk",
    category: "warmup",
    movementPattern: "mixed",
    nodeTypes: ["warmup_neural", "warmup_reset"],
    velocitySupported: false,
  },
  hip_bridge: {
    id: "hip_bridge",
    title: "Hip Bridge",
    category: "warmup",
    movementPattern: "hinge",
    nodeTypes: ["warmup_neural", "warmup_reset"],
    velocitySupported: false,
  },
  split_squat_iso: {
    id: "split_squat_iso",
    title: "Split Squat ISO",
    category: "isometric",
    movementPattern: "split_squat",
    nodeTypes: ["warmup_neural", "support_isometric"],
    velocitySupported: false,
  },
  ninety_ninety_breathing: {
    id: "ninety_ninety_breathing",
    title: "90/90 Breathing",
    category: "recovery",
    movementPattern: "breathing",
    nodeTypes: ["warmup_reset", "recovery_reset"],
    velocitySupported: false,
  },
  pallof_press: {
    id: "pallof_press",
    title: "Pallof Press",
    category: "warmup",
    movementPattern: "core",
    nodeTypes: ["warmup_neural", "warmup_reset"],
    velocitySupported: false,
  },
};

export const NODE_DEFINITIONS: Record<string, TrainingNodeDefinition> = {
  warmup_neural: {
    id: "warmup_neural",
    type: "warmup_neural",
    label: "Neural Warmup",
    description: "Activation block before high-quality work.",
    intentTags: ["FORCE", "FORCE_POWER", "POWER", "PRIMER"],
    defaultOrder: 10,
    required: true,
    exerciseSlots: [
      {
        slotId: "warmup_sequence",
        label: "Warmup Sequence",
        allowedCategories: ["warmup", "isometric"],
        exercisePoolIds: ["mini_band_glute_walk", "hip_bridge", "split_squat_iso", "pallof_press"],
        select: { mode: "multi", min: 2, max: 4 },
      },
    ],
    baseProfile: {
      status: "active",
      setRep: { setsMin: 1, setsMax: 2, repsMin: 6, repsMax: 10 },
      velocity: null,
      notes: ["Always prepare core and hip stiffness before primer work."],
    },
    stateProfiles: {
      GREEN_PLUS: { status: "active" },
      GREEN: { status: "active" },
      YELLOW: { status: "active", setRep: { setsMin: 1, setsMax: 1, repsMin: 6, repsMax: 8 } },
      RED: { status: "replaced", notes: ["Use reset-oriented warmup instead."] },
    },
    replacementNodeTypeForRed: "warmup_reset",
  },
  warmup_reset: {
    id: "warmup_reset",
    type: "warmup_reset",
    label: "Reset Warmup",
    description: "Low-cost reset and breathing warmup.",
    intentTags: ["RECOVERY", "RESET", "PRIMER"],
    defaultOrder: 10,
    required: true,
    exerciseSlots: [
      {
        slotId: "reset_sequence",
        label: "Reset Sequence",
        allowedCategories: ["recovery", "warmup"],
        exercisePoolIds: ["ninety_ninety_breathing", "mini_band_glute_walk", "hip_bridge"],
        select: { mode: "multi", min: 2, max: 3 },
      },
    ],
    baseProfile: {
      status: "active",
      setRep: { setsMin: 1, setsMax: 2, repsMin: 4, repsMax: 8 },
      velocity: null,
      notes: ["Use on RED or no-input days to reduce nervous system cost."],
    },
    stateProfiles: {
      GREEN_PLUS: { status: "reduced" },
      GREEN: { status: "reduced" },
      YELLOW: { status: "active" },
      RED: { status: "active" },
    },
  },
  primer_ballistic: {
    id: "primer_ballistic",
    type: "primer_ballistic",
    label: "Ballistic Primer",
    intentTags: ["PRIMER", "POWER", "FORCE_POWER"],
    defaultOrder: 20,
    required: false,
    exerciseSlots: [
      {
        slotId: "ballistic",
        label: "Ballistic",
        allowedCategories: ["primer", "plyometric", "strength"],
        allowedMovementPatterns: ["jump", "pull"],
        exercisePoolIds: ["jump_shrug", "mid_thigh_pull", "db_snatch", "box_jump", "drop_jump"],
        select: { mode: "single", min: 1, max: 1 },
      },
    ],
    baseProfile: {
      status: "active",
      setRep: { setsMin: 4, setsMax: 4, repsMin: 2, repsMax: 3 },
      velocity: {
        zoneKey: "BALLISTIC",
        targetMin: 1.1,
        targetMax: null,
        velocityLossCap: 0.1,
        stopSetOnVelocityLoss: true,
      },
      rest: { intraSetSeconds: 20, betweenSetSecondsMin: 60, betweenSetSecondsMax: 90 },
      notes: ["Ballistic quality first, terminate set when quality drops."],
    },
    stateProfiles: {
      GREEN_PLUS: {
        status: "active",
        setRep: { setsMin: 4, setsMax: 4, repsMin: 2, repsMax: 3 },
      },
      GREEN: {
        status: "active",
        setRep: { setsMin: 4, setsMax: 4, repsMin: 2, repsMax: 3 },
      },
      YELLOW: {
        status: "reduced",
        setRep: { setsMin: 3, setsMax: 3, repsMin: 2, repsMax: 2 },
        rest: { intraSetSeconds: 20, betweenSetSecondsMin: 30, betweenSetSecondsMax: 60 },
      },
      RED: {
        status: "disabled",
        notes: ["No ballistic primer in RED state."],
      },
    },
    mdModifiers: {
      MD2: {
        setRep: { setsMin: 3, setsMax: 3, repsMin: 2, repsMax: 2 },
        velocity: { zoneKey: "POWER", targetMin: 0.95, targetMax: 1.05, velocityLossCap: 0.1, stopSetOnVelocityLoss: true },
      },
      MD1: {
        setRep: { setsMin: 2, setsMax: 2, repsMin: 2, repsMax: 2 },
        velocity: { zoneKey: "POWER", targetMin: 0.95, targetMax: 1.05, velocityLossCap: 0.05, stopSetOnVelocityLoss: true },
        rest: { fixedBetweenSetSeconds: 60, intraSetSeconds: 20 },
      },
      MD_PLUS_1: {
        status: "reduced",
        setRep: { setsMin: 1, setsMax: 2, repsMin: 2, repsMax: 2 },
      },
    },
    replacementNodeTypeForRed: "primer_light",
  },
  primer_light: {
    id: "primer_light",
    type: "primer_light",
    label: "Light Primer",
    intentTags: ["PRIMER", "RESET"],
    defaultOrder: 20,
    required: false,
    exerciseSlots: [
      {
        slotId: "light_primer",
        label: "Light Primer",
        allowedCategories: ["warmup", "recovery", "mobility"],
        exercisePoolIds: ["mini_band_glute_walk", "hip_bridge", "pallof_press"],
        select: { mode: "multi", min: 1, max: 2 },
      },
    ],
    baseProfile: {
      status: "active",
      setRep: { setsMin: 1, setsMax: 2, repsMin: 6, repsMax: 10 },
      velocity: null,
      rest: { fixedBetweenSetSeconds: 45 },
      notes: ["Low-cost primer for RED and constrained days."],
    },
    stateProfiles: {
      GREEN_PLUS: { status: "reduced" },
      GREEN: { status: "reduced" },
      YELLOW: { status: "active" },
      RED: { status: "active" },
    },
  },
  main_force_contrast: {
    id: "main_force_contrast",
    type: "main_force_contrast",
    label: "Lower Body Contrast (Force)",
    intentTags: ["FORCE", "FORCE_POWER"],
    defaultOrder: 30,
    required: false,
    exerciseSlots: [
      {
        slotId: "strength",
        label: "Strength",
        allowedCategories: ["strength"],
        allowedMovementPatterns: ["hinge", "split_squat"],
        exercisePoolIds: ["trap_bar_deadlift", "split_stance_trap_bar_deadlift", "rfess"],
        select: { mode: "single", min: 1, max: 1 },
      },
      {
        slotId: "plyo",
        label: "Plyometric",
        allowedCategories: ["plyometric"],
        allowedMovementPatterns: ["jump"],
        exercisePoolIds: ["box_jump", "drop_jump"],
        select: { mode: "single", min: 1, max: 1 },
      },
    ],
    baseProfile: {
      status: "active",
      setRep: { fixedSets: 3, repsMin: 2, repsMax: 3 },
      velocity: {
        zoneKey: "STRENGTH",
        targetMin: 0.7,
        targetMax: 0.75,
        velocityLossCap: 0.1,
        stopSetOnVelocityLoss: true,
      },
      rest: { betweenSetSecondsMin: 120, betweenSetSecondsMax: 180 },
      notes: ["Stop if velocity loss exceeds cap."],
    },
    stateProfiles: {
      GREEN_PLUS: {
        status: "active",
        setRep: { fixedSets: 4, repsMin: 2, repsMax: 3 },
      },
      GREEN: {
        status: "active",
        setRep: { fixedSets: 3, repsMin: 2, repsMax: 3 },
      },
      YELLOW: {
        status: "reduced",
        setRep: { fixedSets: 2, repsMin: 2, repsMax: 3 },
        velocity: {
          zoneKey: "STRENGTH",
          targetMin: 0.7,
          targetMax: 0.7,
          velocityLossCap: 0.08,
          stopSetOnVelocityLoss: true,
        },
        rest: { fixedBetweenSetSeconds: 120 },
      },
      RED: {
        status: "disabled",
        notes: ["No contrast work in RED state."],
      },
    },
    mdModifiers: {
      MD3: {
        velocity: { zoneKey: "STRENGTH", targetMin: 0.7, targetMax: 0.75, velocityLossCap: 0.1, stopSetOnVelocityLoss: true },
      },
      MD2: {
        status: "reduced",
        setRep: { fixedSets: 2, repsMin: 2, repsMax: 2 },
        velocity: { zoneKey: "STRENGTH_SPEED", targetMin: 0.85, targetMax: 0.95, velocityLossCap: 0.1, stopSetOnVelocityLoss: true },
        rest: { fixedBetweenSetSeconds: 120 },
      },
      MD1: {
        status: "disabled",
        notes: ["No heavy contrast loading on MD-1."],
      },
      MD_PLUS_1: {
        status: "disabled",
      },
      OFF: {
        status: "disabled",
      },
    },
    replacementNodeTypeForRed: "support_isometric",
    hardRules: ["GREEN_PLUS contrast max 4 sets", "Never exceed MD velocity loss cap"],
  },
  support_isometric: {
    id: "support_isometric",
    type: "support_isometric",
    label: "Support Isometrics",
    intentTags: ["FORCE", "RECOVERY", "RESET", "PRIMER", "FORCE_POWER"],
    defaultOrder: 40,
    required: true,
    exerciseSlots: [
      {
        slotId: "iso_support",
        label: "ISO Support",
        allowedCategories: ["isometric"],
        exercisePoolIds: ["hamstring_iso", "copenhagen_iso", "ankle_iso", "iso_mid_thigh_pull", "split_squat_iso"],
        select: { mode: "multi", min: 2, max: 3 },
      },
    ],
    baseProfile: {
      status: "active",
      setRep: { fixedSets: 3, repsMin: 1, repsMax: 1 },
      velocity: null,
      notes: ["Holds 20-45s each rep based on athlete readiness."],
    },
    stateProfiles: {
      GREEN_PLUS: { status: "active", setRep: { fixedSets: 3 } },
      GREEN: { status: "active", setRep: { fixedSets: 3 } },
      YELLOW: { status: "reduced", setRep: { fixedSets: 2 } },
      RED: { status: "active", setRep: { fixedSets: 2 } },
    },
  },
  recovery_reset: {
    id: "recovery_reset",
    type: "recovery_reset",
    label: "Recovery Reset",
    intentTags: ["RECOVERY", "RESET"],
    defaultOrder: 50,
    required: false,
    exerciseSlots: [
      {
        slotId: "recovery",
        label: "Recovery",
        allowedCategories: ["recovery", "mobility", "isometric"],
        exercisePoolIds: ["ninety_ninety_breathing", "hamstring_iso", "ankle_iso", "copenhagen_iso"],
        select: { mode: "multi", min: 2, max: 3 },
      },
    ],
    baseProfile: {
      status: "active",
      setRep: { setsMin: 1, setsMax: 2, repsMin: 1, repsMax: 2 },
      velocity: null,
      rest: { fixedBetweenSetSeconds: 30 },
      notes: ["Low intensity breathing and recovery focus."],
    },
    stateProfiles: {
      GREEN_PLUS: { status: "disabled" },
      GREEN: { status: "disabled" },
      YELLOW: { status: "reduced" },
      RED: { status: "active" },
    },
  },
};

export const BLUEPRINTS: Record<string, TrainingBlueprint> = {
  md3_lower_force: {
    id: "md3_lower_force",
    title: "MD-3 Lower Force",
    intent: "FORCE_POWER",
    mdContexts: ["MD3", "MD4", "MD5"],
    nodeRefs: [
      { nodeId: "warmup_neural", order: 10 },
      { nodeId: "primer_ballistic", order: 20 },
      { nodeId: "main_force_contrast", order: 30 },
      { nodeId: "support_isometric", order: 40 },
    ],
    tags: ["lower", "force", "contrast"],
  },
  md2_power_primer: {
    id: "md2_power_primer",
    title: "MD-2 Power Primer",
    intent: "PRIMER",
    mdContexts: ["MD2"],
    nodeRefs: [
      { nodeId: "warmup_neural", order: 10 },
      { nodeId: "primer_ballistic", order: 20 },
      { nodeId: "support_isometric", order: 30, optional: true },
    ],
    tags: ["primer", "power"],
  },
  md1_neural_primer: {
    id: "md1_neural_primer",
    title: "MD-1 Neural Primer",
    intent: "PRIMER",
    mdContexts: ["MD1"],
    nodeRefs: [
      { nodeId: "warmup_neural", order: 10 },
      { nodeId: "primer_ballistic", order: 20 },
      { nodeId: "support_isometric", order: 30 },
    ],
    tags: ["matchday", "primer"],
  },
  red_reset_session: {
    id: "red_reset_session",
    title: "RED Reset Session",
    intent: "RESET",
    mdContexts: ["UNKNOWN", "OFF", "MD_PLUS_1", "MD1", "MD2", "MD3", "MD4", "MD5"],
    nodeRefs: [
      { nodeId: "warmup_reset", order: 10 },
      { nodeId: "support_isometric", order: 20 },
      { nodeId: "recovery_reset", order: 30 },
    ],
    tags: ["red", "reset", "recovery"],
  },
};
