import type { AutomationRule } from "./types";

const NOW = new Date().toISOString();

/** High-signal default automation rules with deterministic conditions and cooldowns. */
export const DEFAULT_AUTOMATION_RULES: AutomationRule[] = [
  {
    id: "auto.sync.failed.repeated",
    name: "Repeated sync failure escalation",
    description: "Escalate integration sync failures after repeated failed state updates.",
    status: "ENABLED",
    triggerType: "DOMAIN_EVENT",
    scope: "INTEGRATION",
    eventTypes: ["SYNC_JOB_UPDATED", "INTEGRATION_IMPORT_FAILED"],
    conditions: [
      { field: "event.severity", operator: "IN", value: ["WARNING", "CRITICAL"] },
      { field: "event.payload.attemptCount", operator: "GTE", value: 2 },
    ],
    actions: [
      { type: "CREATE_ALERT", config: { severity: "HIGH", title: "Repeated sync failure" } },
      { type: "OPEN_ESCALATION", config: { level: 2 } },
      { type: "FLAG_FOR_ATTENTION" },
    ],
    priority: 90,
    cooldownMinutes: 45,
    requiresHumanReview: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "auto.player.risk.critical.review",
    name: "Critical player risk follow-up",
    description: "Prompt review when player critical risk update occurs.",
    status: "ENABLED",
    triggerType: "DOMAIN_EVENT",
    scope: "PLAYER",
    eventTypes: ["PLAYER_RISK_UPDATED"],
    conditions: [
      { field: "event.payload.injuryRiskBand", operator: "EQ", value: "CRITICAL" },
    ],
    actions: [
      { type: "CREATE_ALERT", config: { severity: "CRITICAL", title: "Critical player risk review needed" } },
      { type: "CREATE_REVIEW_REQUEST" },
      { type: "REQUEST_MANUAL_CONFIRMATION" },
    ],
    priority: 100,
    cooldownMinutes: 120,
    requiresHumanReview: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "auto.session.unseen.followup",
    name: "Published session unseen follow-up",
    description: "Alert when published session has not been seen after configured window.",
    status: "ENABLED",
    triggerType: "DOMAIN_EVENT",
    scope: "WORKFLOW",
    eventTypes: ["SESSION_ASSIGNED"],
    conditions: [
      { field: "event.payload.assignmentStatus", operator: "IN", value: ["ASSIGNED", "DELIVERED"] },
    ],
    actions: [
      { type: "CREATE_ALERT", config: { severity: "NOTICE", title: "Session awaiting player acknowledgement" } },
      { type: "SEND_NOTIFICATION" },
    ],
    priority: 60,
    cooldownMinutes: 180,
    requiresHumanReview: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "auto.review.unresolved.escalate",
    name: "Unresolved review escalation",
    description: "Escalate unresolved review items once they transition to warning state.",
    status: "ENABLED",
    triggerType: "DOMAIN_EVENT",
    scope: "WORKFLOW",
    eventTypes: ["REVIEW_REQUEST_OPENED"],
    conditions: [],
    actions: [
      { type: "CREATE_ALERT", config: { severity: "WARNING", title: "Review request opened" } },
      { type: "OPEN_ESCALATION", config: { level: 1 } },
    ],
    priority: 70,
    cooldownMinutes: 90,
    requiresHumanReview: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "auto.webhook.verification.failure",
    name: "Webhook verification failure",
    description: "Surface rejected webhook events quickly with integration alert.",
    status: "ENABLED",
    triggerType: "DOMAIN_EVENT",
    scope: "INTEGRATION",
    eventTypes: ["WEBHOOK_RECEIVED"],
    conditions: [{ field: "event.payload.status", operator: "EQ", value: "REJECTED" }],
    actions: [
      { type: "CREATE_ALERT", config: { severity: "WARNING", title: "Webhook verification failed" } },
      { type: "FLAG_FOR_ATTENTION" },
    ],
    priority: 85,
    cooldownMinutes: 30,
    requiresHumanReview: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "auto.integration.failure.report",
    name: "Integration failure reporting trigger",
    description: "Queue report generation when integration failures become critical.",
    status: "ENABLED",
    triggerType: "DOMAIN_EVENT",
    scope: "INTEGRATION",
    eventTypes: ["INTEGRATION_IMPORT_FAILED"],
    conditions: [{ field: "event.payload.failedCount", operator: "GTE", value: 5 }],
    actions: [
      { type: "CREATE_ALERT", config: { severity: "HIGH", title: "Critical integration import failure volume" } },
      { type: "GENERATE_REPORT", config: { templateKey: "DELIVERY_WORKFLOW_REPORT" } },
    ],
    priority: 80,
    cooldownMinutes: 240,
    requiresHumanReview: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

