import type { MicroPulseFeatureKey, MicroPulsePlanKey } from "./types";

const FREE_FEATURES: MicroPulseFeatureKey[] = [
  "DAILY_CHECKIN",
  "BASIC_READINESS",
  "PLAYER_MONITORING",
  "TEAM_MONITORING",
];

const PRO_INCREMENTAL_FEATURES: MicroPulseFeatureKey[] = [
  "COACH_DASHBOARD",
  "SQUAD_OVERVIEW",
  "INTELLIGENCE_TAB",
  "LOAD_RPE_TAB",
  "GPS_LOAD_MONITORING",
  "YESTERDAY_LOAD",
  "WEEK_SETUP",
  "ADAPTIVE_TRAINING_ENGINE",
  "NEURAL_FATIGUE_MODEL",
  "PLAYER_VOLATILITY",
  "EXPLAINABLE_DECISIONS",
  "SESSION_ADJUSTMENTS",
  "MATCH_WEEK_LOGIC",
  "TEAM_WORKFLOW",
];

const ELITE_INCREMENTAL_FEATURES: MicroPulseFeatureKey[] = [
  "PERFORMANCE_INTELLIGENCE",
  "INJURY_RISK_MODEL",
  "LOAD_FORECASTING",
  "NEURAL_VOLATILITY_INTELLIGENCE",
  "CROSS_TEAM_ANALYTICS",
  "ORG_DASHBOARDS",
  "EXECUTIVE_REPORTING",
  "MEDICAL_OVERSIGHT",
  "AUTOMATION_ALERTS",
  "ADVANCED_INTEGRATIONS",
  "MULTI_TEAM_MANAGEMENT",
];

const PRO_FEATURES: MicroPulseFeatureKey[] = [...FREE_FEATURES, ...PRO_INCREMENTAL_FEATURES];
const ELITE_FEATURES: MicroPulseFeatureKey[] = [...PRO_FEATURES, ...ELITE_INCREMENTAL_FEATURES];

/**
 * Centralized feature mapping by plan. Keep plan-feature logic here so UI and
 * services do not scatter hardcoded gating checks.
 */
export const PLAN_FEATURES: Record<MicroPulsePlanKey, MicroPulseFeatureKey[]> = {
  FREE: FREE_FEATURES,
  PRO: PRO_FEATURES,
  ELITE: ELITE_FEATURES,
};

export const FEATURE_MIN_PLAN: Record<MicroPulseFeatureKey, MicroPulsePlanKey> = {
  DAILY_CHECKIN: "FREE",
  BASIC_READINESS: "FREE",
  PLAYER_MONITORING: "FREE",
  TEAM_MONITORING: "FREE",
  COACH_DASHBOARD: "PRO",
  ADAPTIVE_TRAINING_ENGINE: "PRO",
  NEURAL_FATIGUE_MODEL: "PRO",
  PLAYER_VOLATILITY: "PRO",
  EXPLAINABLE_DECISIONS: "PRO",
  SESSION_ADJUSTMENTS: "PRO",
  MATCH_WEEK_LOGIC: "PRO",
  TEAM_WORKFLOW: "PRO",
  GPS_LOAD_MONITORING: "PRO",
  YESTERDAY_LOAD: "PRO",
  SQUAD_OVERVIEW: "PRO",
  INTELLIGENCE_TAB: "PRO",
  LOAD_RPE_TAB: "PRO",
  WEEK_SETUP: "PRO",
  PERFORMANCE_INTELLIGENCE: "ELITE",
  INJURY_RISK_MODEL: "ELITE",
  LOAD_FORECASTING: "ELITE",
  NEURAL_VOLATILITY_INTELLIGENCE: "ELITE",
  CROSS_TEAM_ANALYTICS: "ELITE",
  ORG_DASHBOARDS: "ELITE",
  EXECUTIVE_REPORTING: "ELITE",
  MEDICAL_OVERSIGHT: "ELITE",
  AUTOMATION_ALERTS: "ELITE",
  ADVANCED_INTEGRATIONS: "ELITE",
  MULTI_TEAM_MANAGEMENT: "ELITE",
};
