/**
 * Exercise Library — Evidence-based catalog of strength, power, plyometric,
 * unilateral and isometric exercises used by the MicroPulse strength
 * programming engine.
 *
 * Each exercise carries:
 *   - Mechanical profile (eccentric / hinge / max-velocity flags) so
 *     adaptation rules can swap or remove based on player data signals.
 *   - Default per-MD-context dosing (sets × reps × intensity × rest),
 *     driven by sport-science consensus rather than tradition.
 *   - One-line evidence statement with primary citation.
 *
 * Sources: research/ folder (Weightlifting Derivatives, Plyometrics, Cluster
 * Training, Velocity Based Training, Isometric Training, Football, Eccentric
 * Contraction, Rate of Force Development).
 */

import type { Exercise } from "./types";

export const EXERCISE_LIBRARY: Exercise[] = [
  // ── MOVEMENT PREP ──────────────────────────────────────────────────────
  {
    id: "mp_glute_activation",
    nameEN: "Glute activation circuit",
    nameIS: "Glute virkjun (hringur)",
    setup: "Banded clamshells, monster walks, hip extension — 30s each.",
    category: "MOVEMENT_PREP",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: false,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-4": { sets: 1, reps: "30s × 4", intensity: "Bodyweight", rest: "15s" },
      "MD-3": { sets: 1, reps: "30s × 4", intensity: "Bodyweight", rest: "15s" },
      "MD-2": { sets: 1, reps: "30s × 3", intensity: "Bodyweight", rest: "15s" },
    },
    evidence:
      "Glute med/min activation primes hip stability for power output (Selkowitz 2013).",
  },
  {
    id: "mp_hip_mobility",
    nameEN: "Hip mobility flow",
    nameIS: "Mjaðmaliðsflæði",
    setup: "90/90 → hip CARs → cossack squat — 5 reps each.",
    category: "MOVEMENT_PREP",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: false,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-4": { sets: 1, reps: "5 × 3", intensity: "Bodyweight", rest: "—" },
      "MD-3": { sets: 1, reps: "5 × 3", intensity: "Bodyweight", rest: "—" },
      "MD-2": { sets: 1, reps: "5 × 2", intensity: "Bodyweight", rest: "—" },
    },
    evidence: "Joint-by-joint mobility prep improves squat depth and force output (Reiman 2014).",
  },
  {
    id: "mp_pogo_warmup",
    nameEN: "Pogo bouncing (warm-up)",
    nameIS: "Pogo (hitun)",
    setup: "Stiff-ankle bouncing in place, minimal ground contact time.",
    category: "MOVEMENT_PREP",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: false,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-4": { sets: 2, reps: "10", intensity: "Reactive", rest: "30s" },
      "MD-3": { sets: 2, reps: "10", intensity: "Reactive", rest: "30s" },
      "MD-2": { sets: 2, reps: "5", intensity: "Reactive", rest: "30s" },
    },
    evidence: "Ankle stiffness primer for plyometric / sprint sessions (Markovic 2007).",
  },

  // ── EXPLOSIVE OLYMPIC DERIVATIVES ──────────────────────────────────────
  // Progression: Jump shrug → Hang high pull → Mid-thigh pull → Hang power
  // clean → DB snatch → Barbell snatch (Suchomel 2017).
  {
    id: "ex_jump_shrug",
    nameEN: "Jump shrug",
    nameIS: "Jump shrug (stökk-axlalyfta)",
    setup: "From mid-thigh, triple extend explosively, no arm pull. Catch is just a shrug.",
    category: "EXPLOSIVE_OLYMPIC",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: true,
    hasHinge: true,
    isClusterCompatible: true,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-3": {
        sets: 4, reps: "3", intensity: "30-40% 1RM (deadlift)",
        rest: "2 min", velocityLossCap: 10,
        cue: "Triple extend hard, no catch.",
      },
      "MD-2": { sets: 3, reps: "3", intensity: "30% 1RM", rest: "2 min" },
    },
    alternatives: ["ex_hang_high_pull", "ex_mid_thigh_pull_dynamic"],
    evidence: "Entry-level weightlifting derivative for RFD (Suchomel & DeWeese 2014).",
  },
  {
    id: "ex_hang_high_pull",
    nameEN: "Hang high pull",
    nameIS: "Hang high pull",
    setup: "From hang position, triple extend and pull bar to chest height.",
    category: "EXPLOSIVE_OLYMPIC",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: true,
    hasHinge: true,
    isClusterCompatible: true,
    technicalDifficulty: "moderate",
    defaultDosing: {
      "MD-3": {
        sets: 4, reps: "3", intensity: "50-60% 1RM (clean)",
        rest: "2-3 min", velocityLossCap: 10,
      },
    },
    alternatives: ["ex_jump_shrug", "ex_hang_power_clean"],
    evidence: "Bridge from jump shrug to full clean — Suchomel 2017.",
  },
  {
    id: "ex_mid_thigh_pull_dynamic",
    nameEN: "Mid-thigh pull (dynamic)",
    nameIS: "Mid-thigh pull (dýnamískt)",
    setup: "Bar at mid-thigh, triple extend with maximal intent. Pull through the hips.",
    category: "EXPLOSIVE_OLYMPIC",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: true,
    hasHinge: true,
    isClusterCompatible: true,
    technicalDifficulty: "moderate",
    defaultDosing: {
      "MD-3": {
        sets: 4, reps: "3", intensity: "60-65% 1RM",
        rest: "3 min", velocityLossCap: 10,
        cue: "Maximal pull intent — bar speed matters more than load.",
      },
    },
    alternatives: ["ex_imtp_iso", "ex_hang_power_clean"],
    evidence: "Mid-thigh pull RFD correlates with sprint and jump performance (Comfort 2015).",
  },
  {
    id: "ex_hang_power_clean",
    nameEN: "Hang power clean",
    nameIS: "Hang power clean",
    setup: "From hang above knees, triple extend and catch in quarter squat.",
    category: "EXPLOSIVE_OLYMPIC",
    primaryChain: "FULL_BODY",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: true,
    hasHinge: true,
    isClusterCompatible: true,
    technicalDifficulty: "high",
    defaultDosing: {
      "MD-3": {
        sets: 4, reps: "3", intensity: "70-80% 1RM",
        rest: "3 min", velocityLossCap: 10,
      },
    },
    alternatives: ["ex_mid_thigh_pull_dynamic", "ex_db_snatch"],
    evidence: "Olympic derivative for RFD development (Cormie 2011).",
  },
  {
    id: "ex_db_snatch",
    nameEN: "DB snatch",
    nameIS: "Handlóð snatch",
    setup: "From floor, single-arm DB snatch overhead in one motion.",
    category: "EXPLOSIVE_OLYMPIC",
    primaryChain: "FULL_BODY",
    isUnilateral: true,
    hasEccentricLoad: false,
    hasMaxVelocity: true,
    hasHinge: true,
    isClusterCompatible: true,
    technicalDifficulty: "moderate",
    defaultDosing: {
      "MD-3": {
        sets: 3, reps: "5 each side", intensity: "RPE 7",
        rest: "2 min",
        cue: "Hip extension first, arm follows.",
      },
    },
    alternatives: ["ex_kb_swing", "ex_hang_power_clean"],
    evidence: "Full-body unilateral power; lower technical barrier than barbell snatch (Suchomel & Stone 2017).",
  },

  // ── PLYOMETRICS ────────────────────────────────────────────────────────
  {
    id: "ex_box_jump",
    nameEN: "Box jump",
    nameIS: "Boxstökk",
    setup: "Vertical jump onto box, soft landing. Step down (no jump down) to protect tendons.",
    category: "PLYOMETRIC",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: true,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-3": { sets: 3, reps: "3", intensity: "Max effort", rest: "90s" },
      "MD-2": { sets: 2, reps: "3", intensity: "Max effort", rest: "90s" },
    },
    alternatives: ["ex_broad_jump", "ex_depth_jump"],
    contraindications: ["knee_injury", "ankle_injury"],
    evidence: "Vertical plyometric improves jump height and sprint speed (Markovic 2007).",
  },
  {
    id: "ex_depth_jump",
    nameEN: "Depth jump",
    nameIS: "Depth jump (fall stökk)",
    setup: "Step off 30-50cm box, immediately rebound vertically with minimal ground contact.",
    category: "PLYOMETRIC",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: true,
    hasMaxVelocity: true,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "high",
    defaultDosing: {
      "MD-3": { sets: 3, reps: "3", intensity: "Max effort, < 250ms contact", rest: "2 min" },
    },
    alternatives: ["ex_box_jump", "ex_broad_jump"],
    contraindications: ["knee_injury", "ankle_injury", "high_decel_burden"],
    evidence: "Stretch-shortening cycle training; RSI > 2.0 indicates readiness (Flanagan & Comyns 2008).",
  },
  {
    id: "ex_broad_jump",
    nameEN: "Broad jump",
    nameIS: "Lengdarstökk",
    setup: "Horizontal jump for distance, stick the landing.",
    category: "PLYOMETRIC",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: true,
    hasHinge: true,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-3": { sets: 3, reps: "3", intensity: "Max distance", rest: "90s" },
    },
    alternatives: ["ex_box_jump"],
    evidence: "Horizontal plyometric — strong sprint transfer (Loturco 2015).",
  },
  {
    id: "ex_single_leg_box_jump",
    nameEN: "Single-leg box jump",
    nameIS: "Einfætt boxstökk",
    setup: "Take off and land on same leg. Soft, controlled.",
    category: "PLYOMETRIC",
    primaryChain: "POSTERIOR",
    isUnilateral: true,
    hasEccentricLoad: false,
    hasMaxVelocity: true,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "moderate",
    defaultDosing: {
      "MD-3": { sets: 3, reps: "4 each side", intensity: "Max effort", rest: "90s" },
    },
    alternatives: ["ex_single_leg_broad_jump"],
    contraindications: ["knee_injury", "ankle_injury"],
    evidence: "Unilateral plyo; primary tool for L/R power asymmetry (Bishop 2020).",
  },
  {
    id: "ex_lateral_bound",
    nameEN: "Lateral bound",
    nameIS: "Hliðarstökk",
    setup: "Push off one leg laterally, land on opposite leg, stick.",
    category: "PLYOMETRIC",
    primaryChain: "POSTERIOR",
    isUnilateral: true,
    hasEccentricLoad: true,
    hasMaxVelocity: true,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "moderate",
    defaultDosing: {
      "MD-3": { sets: 3, reps: "5 each side", intensity: "Max distance", rest: "60s" },
    },
    evidence: "Frontal plane plyo — change-of-direction transfer (Dos'Santos 2019).",
  },

  // ── BALLISTIC ──────────────────────────────────────────────────────────
  {
    id: "ex_trap_bar_jump_squat",
    nameEN: "Trap-bar jump squat",
    nameIS: "Trap-bar stökk-hnébeygja",
    setup: "Load trap bar, jump as high as possible. Land soft.",
    category: "BALLISTIC",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: true,
    hasHinge: true,
    isClusterCompatible: true,
    technicalDifficulty: "moderate",
    defaultDosing: {
      "MD-3": {
        sets: 3, reps: "3", intensity: "20% 1RM (optimal-power load)",
        rest: "2 min", velocityLossCap: 10,
        cue: "Maximum bar velocity — drop load if velocity falls.",
      },
      "MD-2": { sets: 2, reps: "3", intensity: "Bar only", rest: "90s" },
    },
    alternatives: ["ex_jump_shrug", "ex_kb_swing"],
    evidence: "Optimal-power load ~20% 1RM produces peak power (Loturco 2019).",
  },
  {
    id: "ex_kb_swing",
    nameEN: "Kettlebell swing (heavy)",
    nameIS: "Þung kettlebell sveifla",
    setup: "Hip-hinge swing to chest height (Russian) with explosive hip drive.",
    category: "BALLISTIC",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: true,
    hasMaxVelocity: true,
    hasHinge: true,
    isClusterCompatible: true,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-3": { sets: 4, reps: "8", intensity: "32 kg", rest: "90s" },
    },
    alternatives: ["ex_trap_bar_jump_squat", "ex_hip_thrust"],
    evidence: "Hip-extension power; high RFD output (Otto 2012).",
  },

  // ── MED-BALL ───────────────────────────────────────────────────────────
  {
    id: "ex_mb_rotational_throw",
    nameEN: "Med-ball rotational throw",
    nameIS: "Med-ball snúningskast",
    setup: "Side-on stance, rotate hips and throw med ball at wall with intent.",
    category: "MED_BALL",
    primaryChain: "TRUNK",
    isUnilateral: true,
    hasEccentricLoad: false,
    hasMaxVelocity: true,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-3": { sets: 3, reps: "4 each side", intensity: "4-6 kg", rest: "60s" },
    },
    evidence: "Rotational power; transfers to CoD and kicking velocity (McKinlay 2018).",
  },
  {
    id: "ex_mb_scoop_throw",
    nameEN: "Med-ball scoop throw",
    nameIS: "Med-ball lyftukast (vertical)",
    setup: "Quarter squat with med ball, explode upward and release overhead.",
    category: "MED_BALL",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: true,
    hasHinge: true,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-3": { sets: 3, reps: "5", intensity: "4-6 kg", rest: "60s" },
    },
    evidence: "Vertical triple-extension power without spinal load (Stockbrugger 2003).",
  },
  {
    id: "ex_mb_slam",
    nameEN: "Med-ball overhead slam",
    nameIS: "Med-ball gólfslamm",
    setup: "Reach overhead with med ball, slam down hard with full body.",
    category: "MED_BALL",
    primaryChain: "TRUNK",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: true,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-3": { sets: 3, reps: "5", intensity: "5-7 kg", rest: "60s" },
    },
    evidence: "Anterior chain power output; concentric-dominant for low recovery cost.",
  },

  // ── COMPOUND STRENGTH ──────────────────────────────────────────────────
  {
    id: "ex_trap_bar_dl",
    nameEN: "Trap-bar deadlift",
    nameIS: "Trap-bar deadlift",
    setup: "Neutral spine, push floor away. Drive hips through at top.",
    category: "COMPOUND_STRENGTH",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: true,
    hasMaxVelocity: false,
    hasHinge: true,
    isClusterCompatible: true,
    technicalDifficulty: "moderate",
    defaultDosing: {
      "MD-4": {
        sets: 5, reps: "3", intensity: "85% 1RM / RPE 8",
        rest: "3 min", intraRepRestSec: 25, velocityLossCap: 20,
        cue: "Cluster: 3 reps, 25s pause, repeat as singles within set.",
      },
    },
    alternatives: ["ex_back_squat", "ex_front_squat", "ex_hip_thrust"],
    contraindications: ["lower_back_pain", "sore_lower_back"],
    evidence: "Hybrid strength/power vs back squat; lower spinal load (Suchomel 2017).",
  },
  {
    id: "ex_back_squat",
    nameEN: "Back squat",
    nameIS: "Bak-hnébeygja",
    setup: "Bar high or low on back, descend to parallel or below, drive up.",
    category: "COMPOUND_STRENGTH",
    primaryChain: "ANTERIOR",
    isUnilateral: false,
    hasEccentricLoad: true,
    hasMaxVelocity: false,
    hasHinge: false,
    isClusterCompatible: true,
    technicalDifficulty: "moderate",
    defaultDosing: {
      "MD-4": {
        sets: 5, reps: "3", intensity: "85% 1RM / RPE 8",
        rest: "3 min", intraRepRestSec: 25, velocityLossCap: 20,
      },
      "MD-3": {
        sets: 3, reps: "3", intensity: "80% 1RM",
        rest: "2 min", velocityLossCap: 10,
      },
    },
    alternatives: ["ex_front_squat", "ex_trap_bar_dl", "ex_bulgarian_ss"],
    contraindications: ["lower_back_pain", "knee_injury"],
    evidence: "Foundational max strength — transfers to sprint and jump (Suchomel 2016).",
  },
  {
    id: "ex_front_squat",
    nameEN: "Front squat",
    nameIS: "Fram-hnébeygja",
    setup: "Bar in front rack, elbows up. More quad-dominant than back squat.",
    category: "COMPOUND_STRENGTH",
    primaryChain: "ANTERIOR",
    isUnilateral: false,
    hasEccentricLoad: true,
    hasMaxVelocity: false,
    hasHinge: false,
    isClusterCompatible: true,
    technicalDifficulty: "moderate",
    defaultDosing: {
      "MD-4": {
        sets: 4, reps: "5", intensity: "75% 1RM / RPE 8",
        rest: "2-3 min", intraRepRestSec: 20, velocityLossCap: 20,
      },
    },
    alternatives: ["ex_back_squat", "ex_goblet_squat"],
    contraindications: ["lower_back_pain"],
    evidence: "Quad-biased squat — substitute for back squat when lower back is loaded (Gullett 2009).",
  },
  {
    id: "ex_hip_thrust",
    nameEN: "Hip thrust (barbell)",
    nameIS: "Mjaðmaspark (stöng)",
    setup: "Upper back on bench, bar across hips, drive hips to ceiling.",
    category: "COMPOUND_STRENGTH",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: false,
    hasHinge: true,
    isClusterCompatible: true,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-4": { sets: 4, reps: "6", intensity: "RPE 8", rest: "2 min" },
      "MD-3": { sets: 3, reps: "5", intensity: "RPE 7", rest: "90s" },
    },
    alternatives: ["ex_single_leg_hip_thrust", "ex_trap_bar_dl"],
    evidence: "Glute max activation — correlates with sprint speed (Contreras 2017).",
  },

  // ── UNILATERAL STRENGTH ────────────────────────────────────────────────
  {
    id: "ex_bulgarian_ss",
    nameEN: "Bulgarian split squat",
    nameIS: "Bulgarian split squat",
    setup: "Rear foot elevated on bench, descend on front leg, drive through heel.",
    category: "UNILATERAL_STRENGTH",
    primaryChain: "ANTERIOR",
    isUnilateral: true,
    hasEccentricLoad: true,
    hasMaxVelocity: false,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-4": { sets: 3, reps: "8 each side", intensity: "RPE 8", rest: "90s" },
    },
    alternatives: ["ex_reverse_lunge", "ex_step_up"],
    contraindications: ["knee_injury"],
    evidence: "Unilateral force ~80% of bilateral squat with lower spinal load (Speirs 2016).",
  },
  {
    id: "ex_b_stance_rdl",
    nameEN: "B-stance RDL",
    nameIS: "B-stance RDL (einfótar-biased)",
    setup: "Kickstand stance, ~70% load on front leg, hip hinge with neutral spine.",
    category: "UNILATERAL_STRENGTH",
    primaryChain: "POSTERIOR",
    isUnilateral: true,
    hasEccentricLoad: true,
    hasMaxVelocity: false,
    hasHinge: true,
    isClusterCompatible: false,
    technicalDifficulty: "moderate",
    defaultDosing: {
      "MD-4": { sets: 3, reps: "8 each side", intensity: "RPE 8", rest: "90s" },
      "MD-3": { sets: 3, reps: "6 each side", intensity: "RPE 7", rest: "90s" },
    },
    alternatives: ["ex_single_leg_rdl", "ex_trap_bar_dl"],
    contraindications: ["sore_hamstrings", "hamstring_injury", "lower_back_pain"],
    evidence: "Single-leg-biased hinge for asymmetry correction (Helms 2020).",
  },
  {
    id: "ex_single_leg_rdl",
    nameEN: "Single-leg RDL",
    nameIS: "Einfætta RDL",
    setup: "Stand on one leg, hinge at hip while keeping spine neutral. DB in opposite hand.",
    category: "UNILATERAL_STRENGTH",
    primaryChain: "POSTERIOR",
    isUnilateral: true,
    hasEccentricLoad: true,
    hasMaxVelocity: false,
    hasHinge: true,
    isClusterCompatible: false,
    technicalDifficulty: "high",
    defaultDosing: {
      "MD-4": { sets: 3, reps: "6 each side", intensity: "RPE 7", rest: "60s" },
    },
    alternatives: ["ex_b_stance_rdl"],
    contraindications: ["sore_hamstrings", "hamstring_injury"],
    evidence: "Posterior chain + balance challenge — RTS staple (Helms 2020).",
  },
  {
    id: "ex_reverse_lunge",
    nameEN: "Reverse lunge",
    nameIS: "Afturábak step",
    setup: "Step back, drop rear knee to floor, drive up through front heel.",
    category: "UNILATERAL_STRENGTH",
    primaryChain: "ANTERIOR",
    isUnilateral: true,
    hasEccentricLoad: true,
    hasMaxVelocity: false,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-4": { sets: 3, reps: "8 each side", intensity: "RPE 7", rest: "75s" },
    },
    alternatives: ["ex_bulgarian_ss", "ex_step_up"],
    evidence: "Lower-back-friendly alternative to lunges and Bulgarian SS.",
  },

  // ── POSTERIOR CHAIN ────────────────────────────────────────────────────
  {
    id: "ex_nordic_curl",
    nameEN: "Nordic hamstring curl",
    nameIS: "Nordic hamstring",
    setup: "Kneel with ankles secured. Lower slowly forward, eccentric focus 3-5s.",
    category: "POSTERIOR_CHAIN",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: true,
    hasMaxVelocity: false,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "moderate",
    defaultDosing: {
      "MD-4": {
        sets: 3, reps: "5",
        intensity: "Slow eccentric (3-5s descent)",
        rest: "90s",
        cue: "Control descent — push back up with arms.",
      },
    },
    alternatives: ["ex_iso_ham_bridge_long", "ex_b_stance_rdl"],
    contraindications: ["sore_hamstrings", "hamstring_injury", "high_decel_burden"],
    evidence: "51% reduction in hamstring injuries — strongest evidence in soccer (van Dyk 2019).",
  },
  {
    id: "ex_rdl",
    nameEN: "Romanian deadlift (RDL)",
    nameIS: "Rómversk dauðalyfta (RDL)",
    setup: "Hinge at hip with neutral spine, bar slides down thighs to mid-shin.",
    category: "POSTERIOR_CHAIN",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: true,
    hasMaxVelocity: false,
    hasHinge: true,
    isClusterCompatible: true,
    technicalDifficulty: "moderate",
    defaultDosing: {
      "MD-4": { sets: 4, reps: "6", intensity: "RPE 7-8", rest: "2 min" },
    },
    alternatives: ["ex_trap_bar_dl", "ex_b_stance_rdl"],
    contraindications: ["lower_back_pain"],
    evidence: "Posterior chain hypertrophy + hamstring lengthening (Schoenfeld 2019).",
  },

  // ── ADDUCTOR ───────────────────────────────────────────────────────────
  {
    id: "ex_copenhagen",
    nameEN: "Copenhagen adduction",
    nameIS: "Copenhagen adduction",
    setup: "Side plank with top leg on bench, lift bottom leg up to meet bench.",
    category: "ADDUCTOR",
    primaryChain: "POSTERIOR",
    isUnilateral: true,
    hasEccentricLoad: true,
    hasMaxVelocity: false,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "moderate",
    defaultDosing: {
      "MD-4": {
        sets: 3, reps: "6 each side",
        intensity: "Bodyweight, slow eccentric",
        rest: "60s",
      },
    },
    alternatives: ["ex_sliding_adduction"],
    contraindications: ["groin_injury", "sore_groin"],
    evidence: "41% reduction in groin injuries in elite male soccer (Harøy 2019).",
  },

  // ── ISOMETRIC MAX (RFD) ────────────────────────────────────────────────
  {
    id: "ex_imtp_iso",
    nameEN: "IMTP (Isometric Mid-Thigh Pull)",
    nameIS: "IMTP (kyrrstöðu mid-thigh)",
    setup: "Bar fixed at mid-thigh. Pull maximally for 3-5s. Brief, max-intent efforts.",
    category: "ISOMETRIC_MAX",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: false,
    hasHinge: true,
    isClusterCompatible: true,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-4": { sets: 4, reps: "5s × 1", intensity: "100% MVC", rest: "2-3 min" },
      "MD-3": { sets: 3, reps: "5s × 1", intensity: "100% MVC", rest: "2 min" },
      "MD-2": { sets: 3, reps: "5s × 1", intensity: "100% MVC", rest: "90s" },
      "MD-1": { sets: 2, reps: "3s × 1", intensity: "100% MVC", rest: "90s" },
      "MD+1": { sets: 2, reps: "3s × 1", intensity: "100% MVC", rest: "90s" },
    },
    alternatives: ["ex_iso_squat_90"],
    evidence: "Joint-angle-specific RFD primer; high neural drive, minimal fatigue (Comfort 2018, Lake 2018).",
  },
  {
    id: "ex_iso_squat_90",
    nameEN: "Iso squat hold at 90° knee",
    nameIS: "Kyrr-hnébeygja 90°",
    setup: "Quarter-squat position with 90° knee, hold maximally. Bar or KB optional.",
    category: "ISOMETRIC_MAX",
    primaryChain: "ANTERIOR",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: false,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-4": { sets: 4, reps: "20s", intensity: "80-90% MVC", rest: "2 min" },
      "MD-2": { sets: 3, reps: "15s", intensity: "80% MVC", rest: "90s" },
    },
    alternatives: ["ex_imtp_iso", "ex_iso_split_squat"],
    evidence: "Joint-angle specificity to sprint acceleration phase (Marchetti 2016).",
  },
  {
    id: "ex_iso_split_squat",
    nameEN: "Iso split-stance hold",
    nameIS: "Kyrr-split-stance hold",
    setup: "Split-stance lunge position, back knee 2cm above floor. Hold.",
    category: "ISOMETRIC_MAX",
    primaryChain: "ANTERIOR",
    isUnilateral: true,
    hasEccentricLoad: false,
    hasMaxVelocity: false,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-4": { sets: 3, reps: "30s each side", intensity: "70% MVC", rest: "60s" },
    },
    alternatives: ["ex_iso_squat_90"],
    evidence: "Sport-specific position iso — strong for sprinters (Marchetti 2016).",
  },

  // ── ISOMETRIC LONG-DURATION (tendon stiffness) ─────────────────────────
  {
    id: "ex_spanish_squat",
    nameEN: "Spanish squat",
    nameIS: "Spanish squat",
    setup: "Band around back of knees anchored in front. Squat against band tension.",
    category: "ISOMETRIC_LONG",
    primaryChain: "ANTERIOR",
    isUnilateral: false,
    hasEccentricLoad: true,
    hasMaxVelocity: false,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-4": { sets: 3, reps: "30s", intensity: "70% MVC", rest: "90s" },
    },
    alternatives: ["ex_iso_squat_90"],
    evidence: "Patellar tendon stiffness adaptation; pain-friendly (Lim & Childs 2020).",
  },
  {
    id: "ex_iso_ham_bridge_long",
    nameEN: "Long iso hamstring bridge (single-leg)",
    nameIS: "Lang ham-bridge (einfætt)",
    setup: "Single-leg glute bridge, heel on bench, hold position 30s+.",
    category: "ISOMETRIC_LONG",
    primaryChain: "POSTERIOR",
    isUnilateral: true,
    hasEccentricLoad: false,
    hasMaxVelocity: false,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-4": { sets: 3, reps: "30s each side", intensity: "70% MVC", rest: "60s" },
    },
    alternatives: ["ex_nordic_curl"],
    evidence: "Hamstring tendon adaptation; Nordic alternative when eccentric loading is contraindicated (Lim 2020).",
  },

  // ── ACCESSORY ──────────────────────────────────────────────────────────
  {
    id: "ex_heavy_calf_raise",
    nameEN: "Heavy calf raise",
    nameIS: "Þung kálfa-lyfta",
    setup: "Standing calf raise with barbell or machine, full ROM, controlled descent.",
    category: "ACCESSORY",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: true,
    hasMaxVelocity: false,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-4": { sets: 4, reps: "8", intensity: "RPE 8", rest: "60s" },
    },
    alternatives: ["ex_iso_calf_raise_hold"],
    evidence: "Achilles tendon adaptation; sprint stiffness contributor (Schoenfeld 2019).",
  },
  {
    id: "ex_banded_glute_med",
    nameEN: "Banded glute med (clamshell / side-walk)",
    nameIS: "Glute med með band",
    setup: "Band around knees, side-lying clamshells or standing lateral walks.",
    category: "ACCESSORY",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: false,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-4": { sets: 2, reps: "15 each side", intensity: "Light band", rest: "30s" },
    },
    evidence: "Glute med activation — hip stability for CoD (Selkowitz 2013).",
  },

  // ── MOBILITY ───────────────────────────────────────────────────────────
  {
    id: "ex_mobility_close",
    nameEN: "Mobility close",
    nameIS: "Mobility lokun",
    setup: "Foam roll → couch stretch → hip flexor lengthening → diaphragmatic breathing.",
    category: "MOBILITY",
    primaryChain: "POSTERIOR",
    isUnilateral: false,
    hasEccentricLoad: false,
    hasMaxVelocity: false,
    hasHinge: false,
    isClusterCompatible: false,
    technicalDifficulty: "low",
    defaultDosing: {
      "MD-4": { sets: 1, reps: "8 min", intensity: "Low", rest: "—" },
      "MD-3": { sets: 1, reps: "5 min", intensity: "Low", rest: "—" },
      "MD-2": { sets: 1, reps: "5 min", intensity: "Low", rest: "—" },
    },
    evidence: "Parasympathetic downregulation accelerates recovery (Stanley 2013).",
  },
];

/** Map exercises by ID for O(1) lookup. */
export const EXERCISES_BY_ID: Map<string, Exercise> = new Map(
  EXERCISE_LIBRARY.map((ex) => [ex.id, ex])
);

/** Look up an exercise by ID. Throws if not found — fail fast. */
export function getExercise(id: string): Exercise {
  const ex = EXERCISES_BY_ID.get(id);
  if (!ex) throw new Error(`Unknown exercise id: ${id}`);
  return ex;
}

/** Find all exercises in a category. */
export function getExercisesByCategory(category: Exercise["category"]): Exercise[] {
  return EXERCISE_LIBRARY.filter((ex) => ex.category === category);
}
