import type { Lang } from "@/lib/lang";

export const INDIVIDUAL_TRAINING_COPY = {
  IS: {
    section: {
      title: "Styrktaræfing dagsins",
      subtitle: "Aðlöguð að þinni getu",
    },
    readiness: {
      title: "Aðlögun vegna getu",
      adjusted: "Æfingin hefur verið aðlöguð að þinni getu til þjálfunar",
      zone: {
        green: "Tilbúinn",
        yellow: "Gát",
        red: "Hvíld",
      },
      explanation: "Hvað þýðir þetta?",
    },
    exercise: {
      sets: "Set",
      reps: "Endurtekningar",
      load: "Álag",
      tempo: "Hraði",
      rest: "Hvíld á milli setta",
      notes: "Athugasemdir þjálfarans",
      original: "Upprunalegt",
      adjusted: "Aðlagað",
      kg: "kg",
      ms: "m/s",
      percentage: "%1RM",
      rpe: "RPE",
      logButton: "Skrá æfingu",
      logged: "Skrað",
    },
    logging: {
      title: "Skrá æfingu",
      setsCompleted: "Set lokið",
      repsCompleted: "Endurtekningar loknar",
      loadUsed: "Álag notað",
      rpeActual: "RPE raunveruleg",
      notes: "Athugasemdir",
      submit: "Skrá",
      cancel: "Hætta við",
      success: "Æfingin hefur verið skrád",
      error: "Villa við skráningu",
    },
    overview: {
      week: "Vika",
      of: "af",
      progress: "Framvinda áætlunar",
      day: "Dagur",
    },
    empty: {
      restDay: "Hvíldardagur",
      restDayMessage: "Þú ert á hvíldardag í dag. Njóttu endalaust pipu og endurheimtu þig.",
      noPlan: "Engin áætlun",
      noPlanMessage: "Þú ert ekki með virka þjálfunaráætlun. Hafðu samband við þinn einkaþjálfara.",
      notFound: "Engin gögn",
      loadingError: "Villa við hleðslu",
      tryAgain: "Reyndu aftur",
    },
  },
  EN: {
    section: {
      title: "Today's Strength Session",
      subtitle: "Adjusted for your readiness",
    },
    readiness: {
      title: "Readiness Adjustment",
      adjusted: "Your session has been adjusted based on your readiness level",
      zone: {
        green: "Ready",
        yellow: "Caution",
        red: "Recovery",
      },
      explanation: "What does this mean?",
    },
    exercise: {
      sets: "Sets",
      reps: "Reps",
      load: "Load",
      tempo: "Tempo",
      rest: "Rest between sets",
      notes: "Coach's notes",
      original: "Original",
      adjusted: "Adjusted",
      kg: "kg",
      ms: "m/s",
      percentage: "%1RM",
      rpe: "RPE",
      logButton: "Log Exercise",
      logged: "Logged",
    },
    logging: {
      title: "Log Exercise",
      setsCompleted: "Sets completed",
      repsCompleted: "Reps completed",
      loadUsed: "Load used",
      rpeActual: "Actual RPE",
      notes: "Notes",
      submit: "Log",
      cancel: "Cancel",
      success: "Exercise logged",
      error: "Error logging exercise",
    },
    overview: {
      week: "Week",
      of: "of",
      progress: "Plan progress",
      day: "Day",
    },
    empty: {
      restDay: "Rest Day",
      restDayMessage: "You have a rest day today. Enjoy easy recovery and let your body recover.",
      noPlan: "No Plan",
      noPlanMessage: "You don't have an active training plan. Contact your personal trainer.",
      notFound: "No Data",
      loadingError: "Loading Error",
      tryAgain: "Try Again",
    },
  },
} as const;

export type IndividualTrainingLang = keyof typeof INDIVIDUAL_TRAINING_COPY;
