-- New dedicated PIMA/HIMA isometric exercises (system/global, owner_team_id NULL).
-- PIMA (overcoming): push/pull maximally into immovable pins → max strength + RFD.
-- HIMA (yielding): hold a position against load → tendon health, knee/groin resilience.
-- Idempotent: skip names that already exist.
insert into public.exercise_library (name, name_is, exercise_type, category, movement_family, is_bilateral, description, description_is, owner_team_id)
select * from (values
  (
    'ISO Squat (overcoming)', 'ISO hnébeygja (push)', 'strength', 'compound', 'squat', true,
    $d$Isometric — PIMA (overcoming / pushing): drive a fixed bar maximally upward against pins set in a rack — the bar can't move, so you produce force into it. Set the safety pins so the bar sits at a chosen knee angle (e.g. ~90–120°), bar on the back as for a squat, brace hard, then push up maximally. Builds max strength and rate of force development with high force and minimal fatigue/soreness; gains are strongest near the trained angle. Dosing: maximal intent, short pushes 3–5 s for RFD (up to ~20–30 s for hypertrophy/stiffness), 3–5 reps, full rest; set the pins at the angle (often the sticking point) you want to strengthen. Cues: get tight first, then push as hard and fast as possible, stay in position. Common faults: easing into it, losing the back/brace, and sub-maximal effort.$d$,
    $i$Ísómetrísk — PIMA (overcoming / pushing): ýttu fastri stöng hámarks upp í pinna í grind — stöngin getur ekki hreyfst, svo þú myndar kraft í hana. Stilltu öryggis-pinnana svo stöngin sitji í völdu hné-horni (t.d. ~90–120°), stöng á baki eins og í hnébeygju, spenntu fast og ýttu svo upp hámarks. Byggir hámarksstyrk og kraftmyndunarhraða með háum krafti og lágmarks þreytu/harðsperrum; mestur ávinningur nálægt þjálfuðu horni. Skömmtun: hámarks ásetningur, stutt ýting 3–5 sek fyrir RFD (allt að ~20–30 sek fyrir ofvöxt/stífni), 3–5 endurtekningar, full hvíld; settu pinnana í hornið (oft "sticking point") sem þú vilt styrkja. Cues: spenntu fyrst, ýttu svo eins fast og hratt og hægt er, haltu stöðu. Algeng mistök: fara rólega í það, missa bak/spennu, og hálf-átak.$i$,
    null::uuid
  ),
  (
    'ISO Bench Press (overcoming)', 'ISO bekkpressa (push)', 'strength', 'compound', 'push', true,
    $d$Isometric — PIMA (overcoming / pushing): push a fixed bar maximally upward into pins set in a rack at a chosen elbow angle. Lie as for a bench press, bar against the pins, brace and pull the shoulder blades down, then push up maximally. Builds upper-body max strength and rate of force development at and near the trained angle, with minimal fatigue. Dosing: maximal intent, 3–5 s pushes for RFD (up to ~20 s for stiffness/hypertrophy), 3–5 reps, full rest; set the pins at your weak / sticking point. Cues: brace, drive maximally and fast, keep position. Common faults: ramping up slowly, losing tightness, and sub-maximal effort.$d$,
    $i$Ísómetrísk — PIMA (overcoming / pushing): ýttu fastri stöng hámarks upp í pinna í grind í völdu olnboga-horni. Liggðu eins og í bekkpressu, stöng við pinnana, spenntu og dragðu herðablöð niður, ýttu svo upp hámarks. Byggir hámarksstyrk efri hluta og kraftmyndunarhraða við og nálægt þjálfuðu horni, með lágmarks þreytu. Skömmtun: hámarks ásetningur, 3–5 sek ýting fyrir RFD (allt að ~20 sek fyrir stífni/ofvöxt), 3–5 endurtekningar, full hvíld; settu pinnana á veika / "sticking" punktinn. Cues: spenntu, ýttu hámarks og hratt, haltu stöðu. Algeng mistök: byggja upp hægt, missa spennu, og hálf-átak.$i$,
    null::uuid
  ),
  (
    'Spanish Squat', 'Spænsk hnébeygja', 'strength', 'compound', 'squat', true,
    $d$Isometric — HIMA (holding / yielding): a knee-dominant hold for patellar-tendon health. Loop a stout band around a fixed post and the backs of your knees; sit back into a squat (shins vertical) so the band resists you, and hold the position. Loads the quads/patellar tendon heavily with little spinal load — a well-supported choice for jumper's knee (patellar tendinopathy) and knee resilience. Dosing (tendon, Rio-style): holds 30–45 s, ~4–5 reps, moderate–high effort, often daily for pain relief; progress by adding a held weight. Cues: shins vertical, sit back into the band, big chest, even pressure through the feet. Common faults: knees travelling forward, rising onto the toes, and holding the breath.$d$,
    $i$Ísómetrísk — HIMA (holding / yielding): hné-drifin hold fyrir hnéskeljar-sin heilsu. Settu sterka teygju um fastan staur og aftan við hnén; setstu aftur í hnébeygju (sköflungar lóðréttir) svo teygjan standist þig, og haltu stöðunni. Hleður framlæri/hnéskeljarsin kröftuglega með litlu álagi á hrygg — vel studd val fyrir "jumper's knee" (hnéskeljar-tendinopathy) og hné-þol. Skömmtun (sin, Rio-stíll): hold 30–45 sek, ~4–5 endurtekningar, miðlungs–há áreynsla, oft daglega fyrir verkjalækkun; framfarir með því að halda á lóði. Cues: sköflungar lóðréttir, settu aftur í teygjuna, stór bringa, jafn þrýstingur í gegnum fæturna. Algeng mistök: hné fram, rísa á tær, og halda niðri í sér andanum.$i$,
    null::uuid
  ),
  (
    'Wall Sit', 'Veggseta', 'strength', 'compound', 'squat', true,
    $d$Isometric — HIMA (holding / yielding): sit with your back flat against a wall, thighs parallel and knees ~90° over the ankles, and hold the position against gravity. A simple, joint-friendly quad isometric for strength-endurance, knee resilience and tendon tolerance. Dosing: holds 20–60 s (longer for endurance/tendon), 2–4 reps; progress with time, a held weight, or single-leg. Cues: back flat on the wall, knees over ankles (~90°), even weight, breathe. Common faults: hips creeping up, knees caving in, and holding the breath.$d$,
    $i$Ísómetrísk — HIMA (holding / yielding): sittu með bakið flatt við vegg, læri lárétt og hné ~90° yfir ökklum, og haltu stöðunni gegn þyngdarafli. Einföld, liðvæn framlæris-ísómetría fyrir styrk-þol, hné-þol og sin-þol. Skömmtun: hold 20–60 sek (lengri fyrir þol/sin), 2–4 endurtekningar; framfarir með tíma, lóði í höndum, eða einum fæti. Cues: bak flatt á vegg, hné yfir ökklum (~90°), jöfn þyngd, andaðu. Algeng mistök: mjaðmir skríða upp, hné detta inn, og halda niðri í sér andanum.$i$,
    null::uuid
  ),
  (
    'Adductor Plate Squeeze', 'Aðdráttar-kreista', 'strength', 'isolation', null, true,
    $d$Isometric — HIMA (holding / yielding): squeeze a ball or plate between the knees (or ankles) and hold, contracting the adductors against the object. A simple, low-threat groin isometric for adductor strength and groin-injury prevention — useful early-stage and as a daily primer for footballers. Dosing: maximal-effort squeezes held 5–10 s × 5–10, or longer 20–30 s holds for tolerance, 2–3 sets; supine with knees bent is the easiest start. Cues: squeeze hard and evenly, keep the pelvis level, breathe. Common faults: arching the low back, an uneven squeeze, and holding the breath. (For a harder progression, see the Copenhagen Adductor.)$d$,
    $i$Ísómetrísk — HIMA (holding / yielding): kreistu bolta eða plötu á milli hnjáa (eða ökkla) og haltu, spenntu aðdráttarvöðva gegn hlutnum. Einföld, lág-áhættu nára-ísómetría fyrir aðdráttar-styrk og nára-meiðslavarnir — gagnleg snemma og sem daglegur "primer" fyrir fótboltafólk. Skömmtun: hámarks-kreistur haldnar 5–10 sek × 5–10, eða lengri 20–30 sek hold fyrir þol, 2–3 sett; á baki með bogin hné er auðveldasta byrjun. Cues: kreistu fast og jafnt, haltu mjaðmagrind láréttri, andaðu. Algeng mistök: sveigja mjóbak, ójöfn kreista, og halda niðri í sér andanum. (Fyrir erfiðari framvindu, sjá Copenhagen Adductor.)$i$,
    null::uuid
  )
) as v(name, name_is, exercise_type, category, movement_family, is_bilateral, description, description_is, owner_team_id)
where not exists (select 1 from public.exercise_library e where e.name = v.name);
