-- Jump Shrug: evidence-based bilingual description + demo video.
-- Source: Suchomel et al. (2014) "The Jump Shrug: A Progressive Exercise Into
-- Weightlifting Derivatives", NSCA Strength & Conditioning Journal.
update public.exercise_library set
  video_url = 'https://www.youtube.com/shorts/uhgsixPS0bs',
  description = 'Explosive weightlifting derivative that builds lower-body power and teaches the second pull of the clean/snatch. Start in the power position — bar high on the thighs (just below the hip fold), shoulders back, big chest, tight back. Dip into a controlled countermovement to just above the knee, keeping the bar close and weight through the heels. Then drive explosively through the heels into full triple extension of hip, knee and ankle, jumping off the floor while aggressively shrugging the shoulders — keep the bar close and do NOT pull with the arms. Land in an athletic position and control the bar. Because the bar never rises above the hips, it can be loaded heavier than a clean or high pull, overloading the second pull and rate of force development. Variations: quick countermovement (uses the stretch-shortening cycle) or static start (hold 2–3 s low to remove it). Common faults: pulling/jumping before reaching the power position, hips drifting forward (bar loops away), not finishing full triple extension, and a weak shrug. (Suchomel et al., 2014, NSCA Strength & Conditioning Journal)',
  description_is = 'Sprengin lyftinga-afleiða (weightlifting derivative) sem byggir kraft í neðri hluta líkamans og kennir „second pull" í clean/snatch. Byrjaðu í power-stöðu — stöngin hátt á lærunum (rétt neðan við mjaðmabrot), axlir aftur, stór bringa, þéttur bakur. Dýfðu í stýrða gagnhreyfingu niður rétt fyrir ofan hné, haltu stönginni nálægt og þunga í hælum. Réttu svo sprengilega úr hælunum í fulla þriggja-liða réttu á mjöðm, hné og ökkla — stökktu frá gólfi og yptu öxlum kröftuglega; haltu stönginni nálægt og togaðu EKKI með höndum. Lentu í íþróttastöðu og náðu stjórn á stönginni. Þar sem stöngin fer aldrei upp fyrir mjaðmir má hlaða hana þyngri en clean eða high pull, sem ofhleður „second pull" og kraftmyndunarhraða (RFD). Útfærslur: hröð gagnhreyfing (nýtir teygju-styttingar-hringinn) eða kyrr byrjun (haltu 2–3 sek niðri til að taka hann út). Algeng mistök: toga/stökkva áður en komið er í power-stöðu, mjaðmir fara of framarlega (stöngin sveiflast frá líkama), klára ekki fulla réttu á mjöðm/hné/ökkla, og veikt ypp. (Suchomel o.fl., 2014, NSCA Strength & Conditioning Journal)',
  updated_at = now()
where id = 'b7e5bad3-0d5e-4797-9113-f2e266a307e4';
