-- Richer, cue-based bilingual descriptions for the technique-sensitive power
-- moves used in the Contrast / French-Contrast / Triphasic programmes
-- (weightlifting derivatives + plyometrics). Format mirrors the Jump Shrug:
-- setup → execution → key cues → common faults / safety.

update public.exercise_library set
  description = 'Olympic-lift derivative for whole-body power and rate of force development. Start from the hang — bar at mid-thigh (or just above the knee), shoulders slightly over the bar, big chest, flat back. Push the hips back into a short dip, then explosively extend the hips, knees and ankles (triple extension) and shrug, keeping the bar brushing close to the body. As you finish, pull under the bar and catch it on the front of the shoulders in a quarter-squat with elbows high, then stand. Cues: arms stay relaxed until the legs drive; lead with fast elbows; bar travels straight up and close. Common faults: pulling early with the arms, the bar swinging away from the body, and not finishing full extension before pulling under.',
  description_is = 'Ólympíulyftu-afleiða fyrir heildar-kraft og kraftmyndunarhraða (RFD). Byrjaðu úr hang — stöngin á miðju læri (eða rétt fyrir ofan hné), axlir örlítið yfir stöng, stór bringa, flatur bakur. Ýttu mjöðmum aftur í stutta dýfu, réttu svo sprengilega úr mjöðm, hné og ökkla (þriggja-liða rétta) og yptu öxlum, haltu stönginni þétt við líkamann. Þegar þú klárar, dragðu þig undir stöngina og gríptu hana framan á öxlum í kvart-hnébeygju með háa olnboga, stattu svo upp. Cues: handleggir slakir þar til fæturnir drífa; leiddu með hröðum olnbogum; stöngin fer beint upp og nálægt. Algeng mistök: toga snemma með höndum, stöngin sveiflast frá líkama, og klára ekki fulla réttu áður en farið er undir.'
where name = 'Hang Power Clean';

update public.exercise_library set
  description = 'Single-arm dumbbell weightlifting derivative for explosive whole-body power. From a hinge with the dumbbell hanging between or just in front of the legs, drive the hips and legs explosively (triple extension) to accelerate the dumbbell upward, keeping it close to the body. As it rises, punch the arm to lockout overhead and catch it in a slight squat with a stable shoulder, then stand. Cues: power comes from the legs/hips, not the arm; keep the dumbbell close; punch up and "catch" rather than swing. Common faults: muscling the weight up with the arm (arming it), letting the dumbbell loop out away from the body, and an unstable overhead catch.',
  description_is = 'Ein-handa handlóðs lyftinga-afleiða fyrir sprengin heildar-kraft. Úr hinge með handlóðið hangandi milli eða rétt fyrir framan fæturna, drífðu mjaðmir og fætur sprengilega (þriggja-liða rétta) til að hraða lóðinu upp, haltu því nálægt líkama. Þegar það rís, kýldu handleggnum í læsingu yfir höfði og gríptu í lítilli hnébeygju með stöðuga öxl, stattu svo upp. Cues: krafturinn kemur úr fótum/mjöðm, ekki handlegg; haltu lóðinu nálægt; kýldu upp og „gríptu" frekar en að sveifla. Algeng mistök: rífa þyngdina upp með handlegg, láta lóðið sveiflast frá líkama, og óstöðug grip yfir höfði.'
where name = 'DB Snatch';

update public.exercise_library set
  description = 'Two-foot jump onto a box to train concentric (take-off) lower-body power with a safe landing. Set the box at a height you can land on in a tall, athletic quarter-squat — NOT max height that forces deep hip flexion. Dip into a quick countermovement, swing the arms and explode up through full triple extension, then land softly and quietly on top of the box with knees tracking over the toes. Step down one foot at a time. Cues: use the arm swing, "land like a feather", stick the landing. Safety: do not jump DOWN off the box (high impact) — step down. Common faults: chasing box height, soft/loud landings, and knees caving inward.',
  description_is = 'Tveggja-fóta stökk upp á kassa til að þjálfa concentric (frákast) kraft í neðri hluta með öruggri lendingu. Stilltu kassann í hæð sem þú getur lent á í hárri, íþróttalegri kvart-hnébeygju — EKKI hámarkshæð sem þvingar djúpa mjaðmabeygju. Dýfðu í hraða gagnhreyfingu, sveiflaðu handleggjum og sprengdu upp í fulla þriggja-liða réttu, lentu svo mjúkt og hljóðlega ofan á kassanum með hné yfir tám. Stígðu niður einn fót í einu. Cues: notaðu handsveifluna, „lentu eins og fjöður", festu lendinguna. Öryggi: ekki stökkva NIÐUR af kassanum (mikið högg) — stígðu niður. Algeng mistök: elta kassahæð, mjúkar/háværar lendingar, og hné sem detta inn.'
where name = 'Box Jump';

update public.exercise_library set
  description = 'Maximal horizontal two-foot jump for explosive hip power and acceleration transfer. Start in an athletic stance, push the hips back into a quick countermovement while swinging the arms back, then explode forward and up through full triple extension, throwing the arms forward. Land in a balanced athletic position, absorbing softly with the hips and knees. Cues: hips back then drive out, big arm swing, "land and stick" under control. Common faults: collapsing or stumbling on landing, knees caving inward, and jumping out flat (too horizontal) instead of out-and-up.',
  description_is = 'Hámarks lárétt tveggja-fóta stökk fyrir sprengin mjaðmakraft og yfirfærslu í hröðun. Byrjaðu í íþróttastöðu, ýttu mjöðmum aftur í hraða gagnhreyfingu á meðan þú sveiflar handleggjum aftur, sprengdu svo fram og upp í fulla þriggja-liða réttu og kastaðu handleggjum fram. Lentu í jafnvægi í íþróttastöðu og mildaðu með mjöðm og hnjám. Cues: mjaðmir aftur svo drífa út, stór handsveifla, „lentu og festu" undir stjórn. Algeng mistök: hrynja eða hrasa við lendingu, hné detta inn, og stökkva of flatt (of lárétt) í stað út-og-upp.'
where name = 'Broad Jump';

update public.exercise_library set
  description = 'High-intensity reactive (shock) plyometric that trains reactive strength and the stretch-shortening cycle. STEP (do not jump) off a low box — start around 30 cm — land on the balls of both feet and immediately rebound into a maximal vertical jump, minimising ground-contact time (a fast "touch and go"). Stay tall and stiff through the ankles and hips; think "off the ground as fast as possible". Cues: minimal ground time, jump UP not just off, stay rigid. Safety/dosing: advanced — needs a solid strength base; not for beginners or low training age. Start low, keep reps low and quality high; stop when ground contact slows.',
  description_is = 'Há-ákefðar reactive (shock) plyometric sem þjálfar reactive-styrk og teygju-styttingar-hringinn. STÍGÐU (ekki stökkva) fram af lágum kassa — byrjaðu um 30 cm — lentu á framfótum beggja fóta og skjóttu strax upp í hámarks lóðrétt stökk, lágmarkaðu snertitíma við jörð (hratt „touch and go"). Vertu hár og stífur í ökklum og mjöðm; hugsaðu „af jörðu eins hratt og hægt er". Cues: lágmarks snertitími, stökktu UPP ekki bara af, vertu stífur. Öryggi/skömmtun: háþróað — þarf góðan styrkgrunn; ekki fyrir byrjendur eða lágan æfingaaldur. Byrjaðu lágt, fáar endurtekningar og há gæði; hættu þegar snertitími lengist.'
where name = 'Depth Jump';

update public.exercise_library set
  description = 'Maximal vertical jump from a squat, training concentric lower-body power. Dip into a quick countermovement (or, in the pause/static variation, hold the bottom 2–3 s to remove the stretch reflex and train pure concentric power), then explode up through full triple extension reaching as tall as possible. Land softly in an athletic quarter-squat, knees over toes. Cues: explode up, reach tall, land quiet. Common faults: a slow or shallow dip, not finishing full extension, and stiff/heavy landings. Use bodyweight or light load with maximal intent.',
  description_is = 'Hámarks lóðrétt stökk úr hnébeygju sem þjálfar concentric kraft í neðri hluta. Dýfðu í hraða gagnhreyfingu (eða, í pásu/static útgáfu, haltu botninum í 2–3 sek til að taka út teygjuviðbragðið og þjálfa hreinan concentric kraft), sprengdu svo upp í fulla þriggja-liða réttu og teygðu þig eins hátt og hægt er. Lentu mjúkt í íþróttalegri kvart-hnébeygju, hné yfir tám. Cues: sprengdu upp, teygðu hátt, lentu hljóðlega. Algeng mistök: hæg eða grunn dýfa, klára ekki fulla réttu, og stífar/þungar lendingar. Notaðu líkamsþyngd eða létt álag með hámarks ásetningi.'
where name = 'Squat Jump';

update public.exercise_library set
  description = 'Explosive push-up that trains upper-body power and rate of force development. From a strong plank with a braced core, lower under control then push so forcefully that the hands leave the floor. Land softly, letting the elbows bend to absorb, and (for reactive variants) immediately push again. Scale by performing from the knees or with the hands elevated on a box. Cues: brace the core (no sagging hips), push hard and fast, soft elbows on landing. Common faults: sagging or piking the hips, a slow descent, and stiff/hard landings on locked arms.',
  description_is = 'Sprengin armbeygja sem þjálfar kraft í efri hluta og kraftmyndunarhraða. Úr sterkri planka með spenntan kjarna, síga niður undir stjórn og ýttu svo svo kröftuglega að hendurnar yfirgefi gólfið. Lentu mjúkt, leyfðu olnbogum að beygjast til að milda, og (í reactive útgáfum) ýttu strax aftur. Skalaðu með því að gera frá hnjám eða með hendur upphækkaðar á kassa. Cues: spenntu kjarnann (engin sigin mjöðm), ýttu fast og hratt, mjúkir olnbogar við lendingu. Algeng mistök: sigin eða upplyft mjöðm, hæg niðurleið, og stífar/harðar lendingar á læstum handleggjum.'
where name = 'Plyo Push-Up';

update public.exercise_library set
  description = 'Repeated two-foot hops over a line of low hurdles, training reactive strength and stiffness. Hop over each hurdle with minimal ground-contact time, landing on the balls of the feet and rebounding instantly like a pogo stick. Stay tall with a rigid trunk and ankles, using a quick arm drive. Cues: spend as little time on the ground as possible, stay tall and stiff, quick feet. Safety/dosing: start with low hurdles and few contacts; prioritise quality of bounce over height or speed; stop when ground time lengthens. Common faults: long, soft ground contacts, collapsing at the ankle/knee, and folding forward at the hips.',
  description_is = 'Endurteknar tveggja-fóta hopp yfir röð af lágum grindum sem þjálfa reactive-styrk og stífni. Hoppaðu yfir hverja grind með lágmarks snertitíma við jörð, lentu á framfótum og skjóttu strax upp eins og pogo-prik. Vertu hár með stífan búk og ökkla, með hraðri handsveiflu. Cues: vertu eins stutt á jörðinni og hægt er, vertu hár og stífur, hraðir fætur. Öryggi/skömmtun: byrjaðu með lágar grindur og fáar snertingar; settu gæði hoppsins ofar hæð eða hraða; hættu þegar snertitími lengist. Algeng mistök: langar, mjúkar snertingar, hrun í ökkla/hné, og að beygja sig fram í mjöðm.'
where name = 'Hurdle Hop';

update public.exercise_library set
  description = 'Ballistic hip-hinge that builds explosive posterior-chain power. Hike the kettlebell back between the legs by pushing the hips back (a hinge, NOT a squat), then snap the hips forward explosively so the glutes and hamstrings float the bell up to chest/eye height — the arms stay relaxed and just guide it. Keep a neutral spine and brace the core; the bell floats weightless at the top, then let it fall and re-hinge. Cues: hinge not squat, snap the hips, exhale at the top, arms are ropes. Common faults: squatting the weight up, lifting with the arms/shoulders (front raise), and rounding or over-arching the lower back.',
  description_is = 'Ballískur mjaðma-hinge sem byggir sprengin kraft í aftari keðju. Sveiflaðu ketilbjöllunni aftur milli fóta með því að ýta mjöðmum aftur (hinge, EKKI hnébeygja), snöggsnúðu svo mjöðmunum fram sprengilega svo rassvöðvar og aftanlæri fleyti bjöllunni upp í bringu-/augnhæð — handleggir slakir og stýra henni bara. Haltu hlutlausum hrygg og spenntum kjarna; bjallan svífur þyngdarlaus efst, láttu hana svo falla og hinge-aðu aftur. Cues: hinge ekki hnébeygja, snöggsnúðu mjöðm, andaðu frá efst, handleggir eru reipi. Algeng mistök: beygja þyngdina upp, lyfta með handleggjum/öxlum (front raise), og kúpa eða of-sveigja mjóbak.'
where name = 'Kettlebell Swing';
