-- Richer, cue-based bilingual descriptions for the weightlifting movement
-- derivatives, from the NSCA Strength & Conditioning Journal technique series
-- (Suchomel, DeWeese, Comfort et al.): clean/snatch pull, hang high pull,
-- mid-thigh pull, isometric mid-thigh pull, and the countermovement/power shrug.
-- Format mirrors the Jump Shrug entry (setup → execution → cues → common faults).

update public.exercise_library set
  description = 'Weightlifting derivative for the first and second pull of the clean — builds whole-body power and triple-extension speed. Set up over the bar with a clean-width grip, flat back, shoulders slightly ahead of the bar, weight mid-foot. First pull: lift the bar off the floor by extending the knees, keeping the back angle constant and the bar close. Transition through the power position (mid-thigh, double-knee bend) with the torso upright. Second pull: explosively extend the hips, knees and ankles (triple extension) and shrug, keeping the bar brushing the body — there is no catch, the bar finishes around the hip/waist. Because there is no catch it can be loaded heavier than a full clean, overloading the pull. Cues: stay over the bar early; patient first pull; finish tall; bar close. Common faults: opening the hips too early, the bar drifting away, and not finishing full extension.',
  description_is = 'Lyftinga-afleiða fyrir fyrsta og annað tog (first/second pull) í clean — byggir heildar-kraft og hraða í þriggja-liða réttu. Komdu yfir stöngina með clean-gripi, flatan bak, axlir örlítið framan við stöng, þunga á miðjum fæti. Fyrsta tog: lyftu stönginni af gólfi með því að rétta hnén, haltu bakhorni föstu og stönginni nálægt. Farðu í gegnum power-stöðu (miðlæri, tvöföld hnébeygja) með uppréttan búk. Annað tog: réttu sprengilega úr mjöðm, hné og ökkla (þriggja-liða rétta) og yptu öxlum, haltu stönginni þétt — engin grip; stöngin endar um mjöðm/mitti. Þar sem ekki er gripið má hlaða þyngra en fullt clean og ofhlaða togið. Cues: vertu yfir stönginni snemma; þolinmótt fyrsta tog; kláraðu hátt; stöng nálægt. Algeng mistök: opna mjöðm of snemma, stöngin sveiflast frá, og klára ekki fulla réttu.'
where id = '302abb51-fd27-4fd3-8fdd-d4c53b168d69';

update public.exercise_library set
  description = 'Weightlifting derivative for the first and second pull of the snatch, with a wide (snatch) grip — whole-body power and triple-extension speed. Set up over the bar, flat back, shoulders over the bar, weight mid-foot. First pull: extend the knees to lift the bar off the floor, back angle constant, bar close. Transition through the power position (mid-thigh) with an upright torso. Second pull: explosively triple-extend the hips, knees and ankles and shrug, keeping the bar close — no catch; the wider grip means the bar finishes a little higher. Removing the catch lets you load heavier than a full snatch, overloading the pull. Cues: patient first pull, stay over the bar, finish tall, bar close. Common faults: early hip opening, the bar swinging away, and incomplete extension.',
  description_is = 'Lyftinga-afleiða fyrir fyrsta og annað tog í snörun (snatch), með breiðu (snatch) gripi — heildar-kraftur og hraði í þriggja-liða réttu. Komdu yfir stöngina, flatur bakur, axlir yfir stöng, þungi á miðjum fæti. Fyrsta tog: réttu hnén til að lyfta stönginni af gólfi, bakhorn fast, stöng nálægt. Farðu í gegnum power-stöðu (miðlæri) með uppréttan búk. Annað tog: réttu sprengilega úr mjöðm, hné og ökkla og yptu öxlum, haltu stönginni nálægt — engin grip; breiðara gripið þýðir að stöngin endar aðeins hærra. Að sleppa gripinu leyfir þyngra álag en fullt snatch og ofhleður togið. Cues: þolinmótt fyrsta tog, vertu yfir stönginni, kláraðu hátt, stöng nálægt. Algeng mistök: of snemma opnun mjaðmar, stöngin sveiflast frá, ófullnægjandi rétta.'
where id = '5fa90af0-02ef-44d9-91a3-6cef4a8ff79b';

update public.exercise_library set
  description = 'Weightlifting derivative that trains the explosive second pull without a catch. From the hang (bar at mid-thigh, just below the hip fold), shoulders over the bar, big chest, flat back. Dip into a short countermovement, then explosively extend the hips, knees and ankles (triple extension) and immediately high-pull: drive the elbows up and out, keeping the bar close, finishing with the bar around chest/sternum height. No catch — accelerate through the whole movement. Removing the catch lets the athlete focus on a fast, complete triple extension. Cues: lean over the bar, fast and tall, lead the pull with high elbows, bar close. Common faults: pulling with the arms before the legs finish, the bar drifting away, and an incomplete extension.',
  description_is = 'Lyftinga-afleiða sem þjálfar sprengið annað tog (second pull) án grips. Úr hangstöðu (stöng á miðlæri, rétt neðan við mjaðmabrot), axlir yfir stöng, stór bringa, flatur bakur. Dýfðu í stutta gagnhreyfingu, réttu svo sprengilega úr mjöðm, hné og ökkla (þriggja-liða rétta) og togaðu strax hátt: drífðu olnbogana upp og út, haltu stönginni nálægt, stöngin endar um bringu/bringubein. Engin grip — hraðaðu í gegnum alla hreyfinguna. Að sleppa gripinu leyfir áherslu á hratt, fullkomið þriggja-liða útrétt. Cues: hallaðu yfir stöngina, hratt og hátt, leiddu togið með háum olnbogum, stöng nálægt. Algeng mistök: toga með höndum áður en fæturnir klára, stöngin frá líkama, og ófullnægjandi rétta.'
where id = '4d44d19d-c960-46ca-b9c5-86ab0bb11244';

update public.exercise_library set
  description = 'Concentric-only weightlifting derivative performed from the mid-thigh (power) position — pure second-pull power and a strong overload/potentiation tool. Stand with the bar at mid-thigh, knees slightly bent (~135°), torso upright, shoulders over the bar, weight mid-foot. With no first pull and no countermovement, explosively extend the hips, knees and ankles (triple extension) and shrug, keeping the bar close — no catch. Because there is no catch and no eccentric, it can be heavily overloaded (well above power-clean loads), making it useful for maximal-strength and potentiation work. Cues: stay tall and over the bar, drive through the floor, finish full extension, bar close. Common faults: not finishing full triple extension, re-bending/dipping before the pull, and the bar drifting away from the thighs.',
  description_is = 'Concentric-only lyftinga-afleiða framkvæmd úr miðlæris- (power) stöðu — hreinn second-pull kraftur og öflugt ofhleðslu-/potentiation-verkfæri. Stattu með stöngina á miðlæri, hné örlítið beygð (~135°), uppréttur búkur, axlir yfir stöng, þungi á miðjum fæti. Án fyrsta togs og án gagnhreyfingar, réttu sprengilega úr mjöðm, hné og ökkla (þriggja-liða rétta) og yptu öxlum, haltu stönginni nálægt — engin grip. Þar sem ekkert grip er og engin eccentric má ofhlaða verulega (vel yfir power-clean álag), gagnlegt fyrir hámarksstyrk og potentiation. Cues: vertu hár og yfir stönginni, drífðu í gegnum gólfið, kláraðu fulla réttu, stöng nálægt. Algeng mistök: klára ekki fulla réttu, beygja/dýfa aftur fyrir togið, og stöngin sveiflast frá lærunum.'
where id = '5b8439b5-5d72-480a-b201-57459b02bd27';

update public.exercise_library set
  description = 'Isometric maximal-strength test and exercise: pull as hard as possible against a fixed bar set at the mid-thigh (power) position. Set the bar (in a rack / on pins) at the mid-thigh with knees ~125–145° and hips ~140–150°, torso upright, shoulders over the bar, a flat braced back. On the call, build tension then pull maximally into the bar — "push the floor away" — for ~3–5 s, holding the position. Primarily an assessment of peak force and rate of force development (and an isometric strength stimulus). Cues: get tight before pulling, maximal intent, hold the position (do not yank). Common faults: a pre-pull countermovement/jerk, losing the back position, and submaximal effort. Standardise bar height and posture so results are comparable over time.',
  description_is = 'Ísómetrískt hámarksstyrks-próf og æfing: togaðu eins fast og hægt er í fasta stöng í miðlæris- (power) stöðu. Stilltu stöngina (í grind / á pinna) á miðlæri með hné ~125–145° og mjöðm ~140–150°, uppréttan búk, axlir yfir stöng, flatan spenntan bak. Á merki byggðu spennu og togaðu svo hámarks í stöngina — "ýttu gólfinu frá" — í ~3–5 sek og haltu stöðunni. Aðallega mat á hámarkskrafti og kraftmyndunarhraða (RFD) (og ísómetrískt styrktaráreiti). Cues: vertu spenntur áður en þú togar, hámarks ásetningur, haltu stöðunni (ekki kippa). Algeng mistök: gagnhreyfing/kippur fyrir tog, missa bakstöðu, og hálf-átak. Staðlaðu stangarhæð og stöðu svo niðurstöður séu samanburðarhæfar yfir tíma.'
where id = 'f387fa30-1dba-40c8-b9ff-5a25adc11129';

update public.exercise_library set
  description = 'Grounded shrug derivative that overloads the top of the second pull using the stretch-shortening cycle. From a tall standing position with the bar at the hips (power-position grip), dip into a quick countermovement at the hips and knees, then explosively extend (triple extension) and aggressively shrug the shoulders up — keep the bar close and the arms relaxed (do not pull with the arms). Unlike the jump shrug the feet stay on (or barely leave) the floor, so it can be loaded heavier while still training a fast, complete shrug and extension. Cues: quick dip, snap up tall, shrug hard, bar close. Common faults: pulling with the arms (turning it into an upright row), a slow dip, and an incomplete shrug/extension.',
  description_is = 'Jarðbundin axlayftu-afleiða (shrug) sem ofhleður topp annars togs með teygju-styttingar-hringnum. Úr hárri standandi stöðu með stöngina við mjaðmir (power-grip), dýfðu í hraða gagnhreyfingu í mjöðm og hné, réttu svo sprengilega (þriggja-liða rétta) og yptu öxlunum kröftuglega upp — haltu stönginni nálægt og handleggjum slökum (togaðu ekki með höndum). Ólíkt jump shrug haldast fæturnir á (eða yfirgefa varla) gólfið, svo má hlaða þyngra en samt þjálfa hratt, fullkomið ypp og réttu. Cues: hröð dýfa, snöggt upp og hátt, yptu fast, stöng nálægt. Algeng mistök: toga með höndum (verður upright row), hæg dýfa, og ófullnægjandi ypp/rétta.'
where id = '5ef1dcf4-9b99-4b1d-9521-bb57abdcc42f';
