-- Define the isometric exercises by action type — PIMA (pushing/overcoming:
-- push or pull maximally into an immovable resistance → agonist strength + RFD)
-- vs HIMA (holding/yielding: hold a position against a load → more motor
-- control, tendon/resilience, time-efficient) — with evidence-based dosing
-- (intensity %MVC, hold duration, joint-angle specificity).
-- Sources: Schaefer & Bittmann (pushing vs holding isometrics); Oranchuk 2019;
-- Kubo 2001; Rio 2015 (tendon pain); Lum/West (IMTP). Dollar-quoted to keep
-- apostrophes/quotes intact.

update public.exercise_library set
  description = $d$Isometric — PIMA (overcoming / pushing): you pull maximally into a fixed bar, producing force against an immovable resistance. Set the bar (rack/pins) at the mid-thigh power position, knees ~125–145°, hips ~140–150°, torso upright, shoulders over the bar, flat braced back. Get tight, then pull maximally — "push the floor away" — for ~3–5 s. Primarily a max-strength/RFD test and stimulus; PIMA favours agonist (prime-mover) neuromuscular adaptation and longer time-to-failure. Dosing: maximal intent; short holds 3–5 s for RFD, longer (up to ~20–30 s) for tendon stiffness; train near the sport joint angle. Cues: get tight before pulling, maximal effort, hold the position (don't yank). Standardise bar height and posture for comparison.$d$,
  description_is = $i$Ísómetrísk — PIMA (overcoming / pushing): þú togar hámarks í fasta stöng og myndar kraft gegn óhreyfanlegri mótstöðu. Stilltu stöngina (grind/pinnar) í miðlæris-power-stöðu, hné ~125–145°, mjöðm ~140–150°, uppréttur búkur, axlir yfir stöng, flatur spenntur bakur. Spenntu, togaðu svo hámarks — "ýttu gólfinu frá" — í ~3–5 sek. Aðallega hámarksstyrks-/RFD-próf og áreiti; PIMA ýtir undir agonist (aðalvöðva) taugaaðlögun og lengri tíma að þreytu. Skömmtun: hámarks ásetningur; stutt hold 3–5 sek fyrir RFD, lengri (allt að ~20–30 sek) fyrir sin-stífni; æfðu nálægt íþrótta-liðahorni. Cues: spenntu áður en þú togar, hámarks átak, haltu stöðu (ekki kippa). Staðlaðu stangarhæð og stöðu fyrir samanburð.$i$
where id = 'f387fa30-1dba-40c8-b9ff-5a25adc11129';

update public.exercise_library set
  description = $d$Isometric — HIMA (holding / yielding): hold a split-squat position against bodyweight/load, resisting the force that wants to move you. Front thigh roughly parallel, knee over the foot, torso tall, back knee under the hip; brace and hold. HIMA demands more motor control and antagonist/synergist activation and is time-efficient and joint-friendly — useful for unilateral strength, knee/tendon resilience and positional strength. Dosing: moderate–high effort, holds 20–45 s (longer for endurance/tendon, shorter + heavier for strength), 3–4 reps/side at the position you want to strengthen. Cues: stay tall, knee tracking over the foot, even weight, breathe. Common faults: knee caving in, hips shifting, holding the breath.$d$,
  description_is = $i$Ísómetrísk — HIMA (holding / yielding): haltu split-squat stöðu gegn líkamsþyngd/álagi og standist kraftinn sem vill hreyfa þig. Fremra læri nokkurn veginn lárétt, hné yfir fæti, uppréttur búkur, aftara hné undir mjöðm; spenntu og haltu. HIMA krefst meiri hreyfistjórnar og antagonist-/synergist-virkjunar, er tímahagkvæm og liðvæn — gagnleg fyrir einhliða styrk, hné-/sin-þol og stöðu-styrk. Skömmtun: miðlungs–há áreynsla, hold 20–45 sek (lengri fyrir þol/sin, styttri + þyngri fyrir styrk), 3–4 endurtekningar/hlið í stöðunni sem þú vilt styrkja. Cues: vertu hár, hné yfir fæti, jöfn þyngd, andaðu. Algeng mistök: hné inn, mjaðmir færast, halda niðri í sér andanum.$i$
where id = '9528dd44-ea13-4bf4-a9f5-678f5138324d';

update public.exercise_library set
  description = $d$Isometric — HIMA (holding) anterior-core brace. On forearms and toes (or knees to scale), body in one straight line from head to heels, glutes and abs braced, ribs down, no sagging or piking. Hold against gravity. Trains anterior-core stiffness and trunk control to transfer force and protect the spine. Dosing: quality holds 20–45 s (build toward longer for endurance), 2–4 reps; progress with longer holds, added load or harder variations rather than just time. Cues: straight line, brace abs and glutes, ribs down, breathe. Common faults: sagging or piking hips, holding the breath, and shrugged shoulders.$d$,
  description_is = $i$Ísómetrísk — HIMA (holding) fremri-kjarna spenna. Á framhandleggjum og tám (eða hnjám til að létta), líkaminn í beinni línu frá höfði að hælum, rass og kvið spennt, rifbein niður, engin sig eða upplyfting. Haltu gegn þyngdarafli. Þjálfar fremri-kjarna stífni og bolstjórn til að yfirfæra kraft og verja hrygg. Skömmtun: gæða-hold 20–45 sek (byggðu upp í lengri fyrir þol), 2–4 endurtekningar; framfarir með lengri holdum, álagi eða erfiðari útfærslum frekar en bara tíma. Cues: bein lína, spenntu kvið og rass, rifbein niður, andaðu. Algeng mistök: sig eða upplyfting í mjöðm, halda niðri í sér andanum, og uppdregnar axlir.$i$
where id = 'de013fbe-64f4-4ccb-a308-fa9fb58ab135';

update public.exercise_library set
  description = $d$Isometric — HIMA (holding) lateral-core brace. On one forearm and the side of the foot (or bottom knee to scale), body in a straight line, hips lifted and stacked. Hold against gravity — trains the lateral core and hip stabilisers (quadratus lumborum, obliques, gluteus medius). Dosing: 20–45 s/side, 2–3 reps; progress with time, load or reaching variations. Cues: hips high and stacked, straight line, don't let the hips drop. Common faults: hips sagging, rotating forward, and shrugging into the shoulder.$d$,
  description_is = $i$Ísómetrísk — HIMA (holding) hliðar-kjarna spenna. Á einum framhandlegg og hlið fótar (eða neðra hné til að létta), líkaminn í beinni línu, mjaðmir lyftar og staflaðar. Haltu gegn þyngdarafli — þjálfar hliðar-kjarna og mjaðma-stöðugleika (quadratus lumborum, obliques, gluteus medius). Skömmtun: 20–45 sek/hlið, 2–3 endurtekningar; framfarir með tíma, álagi eða teygju-útfærslum. Cues: mjaðmir háar og staflaðar, bein lína, ekki láta mjaðmir síga. Algeng mistök: sig í mjöðm, snúa fram, og draga sig upp í öxlina.$i$
where id = 'd17620aa-2bfa-4ed6-8953-f3b0d8a50919';

update public.exercise_library set
  description = $d$Anti-extension core progression of the plank ("sawing"): from a forearm plank, brace hard and rock the body slightly forward and back over the toes, keeping a straight line and braced trunk throughout — the small movement raises the anterior-core demand. HIMA-style trunk control under a moving lever. Dosing: 8–15 controlled reps or 20–40 s, 2–3 sets. Cues: rigid straight line, brace abs/glutes, small controlled rock, ribs down. Common faults: hips sagging/piking, losing the brace, and too large a range.$d$,
  description_is = $i$Anti-extension kjarna-framvinda úr planka ("sögun"): úr framhandleggja-planka, spenntu fast og veltu líkamanum örlítið fram og aftur yfir tærnar, haltu beinni línu og spenntum bol allan tímann — litla hreyfingin eykur kröfuna á fremri kjarna. HIMA-stíll bolstjórn undir hreyfanlegu vogarafli. Skömmtun: 8–15 stýrðar endurtekningar eða 20–40 sek, 2–3 sett. Cues: stíf bein lína, spenntu kvið/rass, lítil stýrð velta, rifbein niður. Algeng mistök: sig/upplyfting í mjöðm, missa spennuna, og of stórt hreyfisvið.$i$
where id = 'b4096c85-e5eb-437c-bd43-fb138ea032da';

update public.exercise_library set
  description = $d$Isometric — HIMA (holding) anti-rotation core. Hold a load/band offset to one side (e.g. arms extended) and resist the rotation it creates, keeping the trunk square and still. Trains rotational stiffness and trunk control that transfers to throwing, change-of-direction and bracing. Dosing: 15–30 s/side or 5–8 press-and-hold reps, 2–3 sets; increase load/lever to progress. Cues: square the hips and shoulders, brace, don't let the load twist you, breathe. Common faults: rotating/leaning toward the load, shrugging, and holding the breath.$d$,
  description_is = $i$Ísómetrísk — HIMA (holding) anti-rotation kjarni. Haltu álagi/teygju út til hliðar (t.d. útréttir handleggir) og standist snúninginn sem það myndar, haltu bolnum ferköntuðum og kyrrum. Þjálfar snúnings-stífni og bolstjórn sem yfirfærist í köst, stefnubreytingar og spennu. Skömmtun: 15–30 sek/hlið eða 5–8 press-and-hold endurtekningar, 2–3 sett; auktu álag/vogarafl til framfara. Cues: ferkantaðu mjaðmir og axlir, spenntu, ekki láta álagið snúa þér, andaðu. Algeng mistök: snúa/halla að álaginu, draga sig upp, og halda niðri í sér andanum.$i$
where id = '2fe20f97-a6cc-4c23-8c58-87ba77ef93b4';

update public.exercise_library set
  description = $d$Isometric — HIMA (holding) anti-rotation press. Stand side-on to a band/cable at chest height, press the handle straight out and hold, resisting the pull that wants to rotate you — trunk square and still — then return. Builds rotational core stiffness and bracing for sport. Dosing: hold 2–5 s per rep for 8–12 reps, or 20–30 s holds, 2–3 sets/side; step further from the anchor or add tension to progress. Cues: square hips/shoulders, brace, press straight out, resist the twist. Common faults: rotating toward the anchor, leaning, and shrugging the shoulders.$d$,
  description_is = $i$Ísómetrísk — HIMA (holding) anti-rotation press. Stattu hliðar að teygju/kapli í bringuhæð, ýttu handfanginu beint út og haltu, standist togið sem vill snúa þér — bol ferkantaðan og kyrran — og dragðu svo til baka. Byggir snúnings-kjarna stífni og spennu fyrir íþrótt. Skömmtun: haltu 2–5 sek per endurtekningu í 8–12 endurtekningar, eða 20–30 sek hold, 2–3 sett/hlið; stígðu lengra frá festingu eða auktu spennu til framfara. Cues: ferkantaðu mjaðmir/axlir, spenntu, ýttu beint út, standist snúninginn. Algeng mistök: snúa að festingu, halla, og draga upp axlir.$i$
where id = 'e8088efe-5f14-4578-bba5-6c3ac300c5da';

update public.exercise_library set
  description = $d$Isometric — HIMA (holding) adductor/groin exercise. In a side-plank with the top leg supported on a bench, lift the body and hold (or raise/lower) using the bottom-leg adductors, keeping a straight line. Strongly loads the adductors and groin — a key groin-injury-prevention exercise for footballers. Dosing: start with short holds (10–20 s) or partial range, progress to full holds 20–30 s or 6–10 reps/side, 2–3 sets; build load gradually (the groin is injury-prone). Cues: straight line, squeeze the bottom-leg groin, hips up, control. Common faults: hips dropping/rotating, rushing the progression, and pain beyond mild discomfort.$d$,
  description_is = $i$Ísómetrísk — HIMA (holding) nára-/aðdráttar-æfing. Í hliðarplanka með efri fót studdan á bekk, lyftu líkamanum og haltu (eða lyftu/lækkaðu) með aðdráttarvöðvum neðri fótar, haltu beinni línu. Hleður aðdráttarvöðva og nára kröftuglega — lykilæfing í nára-meiðslavörnum fyrir fótboltafólk. Skömmtun: byrjaðu með stuttum holdum (10–20 sek) eða hluta-hreyfisviði, framfarir í full hold 20–30 sek eða 6–10 endurtekningar/hlið, 2–3 sett; auktu álag rólega (nárinn er meiðslagjarn). Cues: bein lína, kreistu nárann á neðri fæti, mjaðmir upp, stjórn. Algeng mistök: mjaðmir síga/snúast, flýta framvindu, og verkur umfram væg óþægindi.$i$
where id = '3be8a64a-196f-43d7-b8b2-a8f5f3c096bf';

update public.exercise_library set
  description = $d$Isometric — HIMA (holding) calf/ankle exercise, often used for Achilles tendon health and pain. Hold a calf-raise (or seated plantarflexion) position against load — e.g. mid-range on one leg — resisting the pull to lower. Isometric loading reduces tendon pain and builds tendon stiffness and load tolerance, valuable in early-stage rehab and prevention. Dosing (tendon, Rio-style): moderate–high effort, holds 30–45 s, ~4–5 reps, 1–2×/day for pain relief; progress load over time. Cues: build tension, hold the position steady, keep the ankle aligned. Common faults: bouncing/letting it drop, rushing, and loading into sharp pain.$d$,
  description_is = $i$Ísómetrísk — HIMA (holding) kálfa-/ökkla-æfing, oft notuð fyrir Achilles-sin heilsu og verki. Haltu kálfalyftu- (eða sitjandi plantarflexion) stöðu gegn álagi — t.d. miðsvið á einum fæti — og standist togið niður. Ísómetrískt álag minnkar sin-verki og byggir sin-stífni og álagsþol, gagnlegt í snemm-rehab og forvörnum. Skömmtun (sin, Rio-stíll): miðlungs–há áreynsla, hold 30–45 sek, ~4–5 endurtekningar, 1–2×/dag fyrir verkjalækkun; auktu álag yfir tíma. Cues: byggðu spennu, haltu stöðu stöðugri, haltu ökkla í línu. Algeng mistök: hoppa/láta síga, flýta sér, og hlaða í skarpan verk.$i$
where id = 'af6f242e-69c3-412c-b08c-f2f7a6bf51e6';

update public.exercise_library set
  description = $d$Isometric — HIMA (holding) hamstring exercise for posterior-chain and hamstring-tendon resilience. Hold a position that loads the hamstrings — e.g. a bridge hold with heels on the floor/bench, a single-leg bridge hold, or a long-lever hold — resisting the load. Builds hamstring strength-endurance and tendon tolerance, useful for hamstring-injury prevention and early rehab. Dosing: holds 20–45 s (up to 60 s for endurance/tendon), 3–4 reps; progress with longer levers, single-leg, or added load. Cues: drive through the heels, squeeze hamstrings/glutes, neutral spine, hold steady. Common faults: cramping from too much too soon, losing neutral spine, and bouncing.$d$,
  description_is = $i$Ísómetrísk — HIMA (holding) aftanlæris-æfing fyrir aftari-keðju og aftanlæris-sin þol. Haltu stöðu sem hleður aftanlæri — t.d. brú-hold með hælum á gólfi/bekk, ein-fóta brú-hold, eða langt-vogarafl hold — og standist álagið. Byggir aftanlæris styrk-þol og sin-þol, gagnlegt fyrir aftanlæris-meiðslavarnir og snemm-rehab. Skömmtun: hold 20–45 sek (allt að 60 sek fyrir þol/sin), 3–4 endurtekningar; framfarir með lengra vogarafli, einum fæti, eða auknu álagi. Cues: drífðu í gegnum hælana, kreistu aftanlæri/rass, hlutlaus hryggur, haltu stöðugt. Algeng mistök: krampi af of miklu of fljótt, missa hlutlausan hrygg, og hoppa.$i$
where id = '0fc107d7-ec7d-43cf-abca-e9410a06f585';
